ynput/ayon-core

client/ayon_core/__init__.py, client/ayon_core/hosts/houdini/api/lib.py, client/ayon_core/hosts/resolve/startup.py, client/ayon_core/lib/local_settings.py, client/ayon_core/modules/job_queue/module.py, client/ayon_core/modules/timers_manager/widget_user_idle.py, client/ayon_core/modules/webserver/webserver_module.py, client/ayon_core/pipeline/farm/patterning.py, client/ayon_core/style/__init__.py, client/ayon_core/tools/traypublisher/window.py
Use AYON in docstrings and labels. Fixed import in houdini. Added `USE_AYON_ENTITIES` which indicates if is used AYON entity structure or OpenPype entity structure (for forwards compatibility).
- Houdini should not complain about missing `cotextmanager`.
- Read changed labels and docstrings.
=> Small addon bugs & enhancements

client/ayon_core/hosts/max/api/pipeline.py
The ported version of this PR in OP Repo. https://github.com/ynput/OpenPype/pull/6200
AYON plugins are not correctly registered when switching to different workspaces. 
n/a
1. launch Max via launcher
2. Open a workfile
3. Switch different workspace
4. Try to publish/load everything to see if it succeeds.
=> Bugfix: AYON menu disappeared when the workspace has been changed in 3dsMax

client/ayon_core/hosts/maya/plugins/publish/validate_rig_joints_hidden.py
Joints Hidden is missing repair action, this adds it back
Paragraphs of text giving context of additional technical information or code examples.
1. enable the Validate Rig Joints Hidden for your current bundle under "ayon+settings://maya/publish/ValidateRigJointsHidden/enabled"
2. Create some visible joints in Maya scene.
3. Create a rig from selection
4. run validation
5. repair action should be available from Report tab
=> Maya: Add repair action to hidden joints validator

client/ayon_core/hosts/aftereffects/api/launch_logic.py, client/ayon_core/hosts/photoshop/api/lib.py, client/ayon_core/hosts/photoshop/plugins/publish/collect_batch_data.py, client/ayon_core/hosts/photoshop/plugins/publish/collect_color_coded_instances.py, client/ayon_core/lib/__init__.py, client/ayon_core/lib/ayon_info.py, client/ayon_core/modules/deadline/plugins/publish/submit_aftereffects_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_blender_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_harmony_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_houdini_cache_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_houdini_render_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_maya_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_maya_remote_publish_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_nuke_deadline.py, client/ayon_core/modules/deadline/plugins/publish/submit_publish_cache_job.py, client/ayon_core/modules/deadline/plugins/publish/submit_publish_job.py, client/ayon_core/modules/royalrender/lib.py, client/ayon_core/pipeline/context_tools.py, client/ayon_core/plugins/publish/cleanup.py, client/ayon_core/plugins/publish/collect_scene_version.py
Fix import from `ayon_core.tests`. Added removed function `is_in_tests` to `ayon_core.lib .
Since we're missing the tests at this moment the function not really necessary, but it is good to have it future ready.
Fixing issue caused by https://github.com/ynput/ayon-core/pull/29
=> Test import fix

client/ayon_core/plugins/publish/collect_from_create_context.py
Do not set environment variables to `None` in `CollectFromCreateContext`.
Set environment variable to `None` is invalid thus the key is removed when the value is not set. This should fix traypublisher collection.
=> Core: Do not force asset and task during publishing

client/ayon_core/hosts/harmony/api/README.md, client/ayon_core/hosts/harmony/api/TB_sceneOpened.js, client/ayon_core/hosts/harmony/api/lib.py, client/ayon_core/settings/defaults/system_settings/applications.json
Use `AYON_` prefix in harmony environment variables.
Replaced `AVALON_HARMONY_WORKFILES_ON_LAUNCH` > `AYON_HARMONY_WORKFILES_ON_LAUNCH` and `AVALON_HARMONY_PORT` > `AYON_HARMONY_PORT`.
=> Harmony: Use AYON prefix in env variables

client/ayon_core/modules/deadline/repository/custom/plugins/Ayon/Ayon.py, client/ayon_core/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py
Add version that is printed in GlobalJobPreLoad plugin.
Sometimes it is hard to debug issues with the plugin, with version printed in the log it should be a little bit easier.
1. Copy new plugin to deadline repository
2. Version should be printed in the job logs
=> Deadline: Version GlobalJobPreLoad

client/ayon_core/hosts/traypublisher/api/editorial.py, client/ayon_core/hosts/traypublisher/api/plugin.py, client/ayon_core/hosts/traypublisher/plugins/create/create_editorial.py, client/ayon_core/settings/ayon_settings.py
Traypublisher does not need AYON settings conversion.
The simple creators did change only single key, the most changes happened in editorial create logic.
1. Run at least one simple creator and publish
2. Create editorial and publish
=> TrayPublisher: Use AYON settings

client/ayon_core/hosts/nuke/api/pipeline.py
Nuke's dirmap is stored under `"dirmap"` instead of `"nuke_dirmap"`.
1. Nuke should not complain about missing `"nuke_dirmap"` key on launch
=> Nuke: Use correct dirmap key

client/ayon_core/pipeline/colorspace.py, client/ayon_core/settings/ayon_settings.py
Imageio settings in hosts does not require conversion.
The changes should be affecting only settings that are used in `colorspace.py`. Modified `colorspace.py` to use AYON data structure. I'm not sure if there is a host which is using directly imageio settings that are handled by `colorspace.py`? I couldn't find any.
I need help with testing notes as I don't know what it in fact affects. Probably validate if imageio is used correctly during publishing?
=> Settings: Host imageio use AYON settings

client/ayon_core/modules/timers_manager/timers_manager.py, client/ayon_core/settings/ayon_settings.py
Timers manager addon can use AYON settings without specific conversion. But still requires some conversion to "disable" the addon by removing it's key from output values.
1. TimersManager can be turned on/off by using version in bundle.
2. Changing settings of timers manager take effect on the addon.
```python
from ayon_core.addon import AddonsManager
manager = AddonsManager()
timers_manager = manager["timers_manager"]
print(timers_manager.time_stop_timer)
>>> Your time from settings * 60
```
=> Timers Manager: Use AYON settings

client/ayon_core/modules/clockify/clockify_module.py, client/ayon_core/settings/ayon_settings.py
Clockify addon can use AYON settings.
Removed clockify addon settings conversion. Clockify addon is using `AYONAddon` as base class. If workspace name is not set, the addon is just disabled (this can be enhanced in future).
1. Clockify addon is enabled/disabled based on selected version in bundle
2. Settings from clockify addon are propagated
=> Clockify: Use AYON settings

client/ayon_core/tools/publisher/widgets/assets_widget.py, client/ayon_core/tools/utils/__init__.py, client/ayon_core/tools/utils/assets_widget.py, client/ayon_core/tools/utils/lib.py
The functions should not be used anywhere else than in assets widget at this moment, moving them to assets widget which is marked as deprecated should make it cleaner that they should not be used.
Just a technical change of functions and related imports.
=> Tools: Move asset icon functions to assets widget

client/ayon_core/lib/applications.py
Add additional applications correctly to list of applications.
Additional applications is not a dictionary but list.
1. Add any additional application in Applications settings
2. It should not raise error when `ApplicationsManager` is created (e.g. in Launcher tool)
=> Applications: Handle additional applications correctly

package.py, server_addon/applications/server/__init__.py, server_addon/create_ayon_addons.py
This commit will modify the `python` script that allows us to quickly generate packages for `ayon-backend` ingestion, either by copying them to the `rez` repo (not advised) or installing them via the `ayon-frontend` by uploading the resulting `zip`s of the script.
This is a PR that will allow us to then test the functionality of this `ayon-backend` PR: https://github.com/ynput/ayon-backend/pull/29
Instead of creating a folder structure at this step, we delegate it to the `rezbuild.py` on the `ayon-backend` which expects the `package.py` and the usual folder structure  of the addon source code (https://github.com/ynput/ayon-addon-template), thus this step is greatly simplified where we only copy the contents of the addon, add a `package.py` and zip them up. 
* 4113ff7bf0 Add `rez` packages …
=> Use new package structure

client/ayon_core/hosts/tvpaint/plugins/publish/extract_sequence.py, server/settings/publish_plugins.py, server_addon/maya/server/settings/loaders.py, server_addon/maya/server/settings/publish_playblast.py, server_addon/tvpaint/server/settings/publish_plugins.py
Fix issue with conversion of settings overrides after [PR](https://github.com/ynput/ayon-core/pull/20).
The issue is that conversion between the color types cannot happen automatically and conversion of overrides for specific version of addon is not yet implemented for addons (I though it is). The biggest difference from current values is that alpha is not used or is used float instead of int, all cases are already handled in code so it is really just change of types in settings. Keeping addon versions as their current version should be what they really are.
New types in models were just commented out as preparation for moment when the conversion of overrides will be working on addons.
1. Create server addons packages.
2. Upload them to server.
3. Try to convert existing overrides to new …
=> Addons: Change color types back to their previous type

server_addon/maya/server/settings/loaders.py
Add missing `ColorRGBA_uint8` import in maya addon.
=> Maya: Fix missing import in Maya addon

server_addon/create_ayon_addons.py
Addon name in package.py does match with real addon name.
The mismatching addon name cause issues when addon is loaded in bundle.
1. Create addons packages
2. Upload royal render package to server
3. Add the addon to bundle
4. The bundle should work correctly and royal render should allow to change settings
=> RoyalRender: Fix addon name in package.py

client/ayon_core/tools/ayon_utils/widgets/__init__.py, client/ayon_core/tools/ayon_utils/widgets/folders_widget.py
implemented base of `SimpleFoldersWidget` as base of possible replacement of `AssetsWidget`.
The api of the widget is not as big as `AssetsWidget` had, and does not contain the default widgets around, like filter input and refresh button. But that should be in different widget and different PR. The implementation is reusing `FoldersWidget` but has implemented simplified controller which fills the values. More api methods can be added when needed.
I had this prepared for a while, but there is need to use it now so I've created quick PR.
=> Tools: Simple folders widget

client/ayon_core/modules/deadline/deadline_module.py, client/ayon_core/modules/deadline/plugins/publish/collect_deadline_server_from_instance.py, client/ayon_core/settings/ayon_settings.py
Deadline addon can use AYON settings.
Modified how 'deadline_urls' are used. It will require more work in future PRs as there were found inconsistencies across the codebase related to deadline urls.
1. Submit to deadline should work.
2. Farm jobs should work.
=> Deadline: Use AYON settings

client/ayon_core/tools/experimental_tools/tools_def.py
Filtering of publisher as experimental host was reduced to "celaction", "flame", "harmony", "hiero" and "resolve", all other hosts are already using it.
=> Experimental Dialog: Reduced filtering hosts for publisher

client/ayon_core/plugins/publish/collect_input_representations_to_versions.py, client/ayon_core/plugins/publish/integrate.py, client/ayon_core/tools/push_to_project/models/integrate.py
Removed usage of `ObjectId` objects.
The usage is not needed anymore and the dependency `bson` is not already defined in pyproject toml.
1. Publish integration should work.
=> Remove 'ObjectId' usage

client/ayon_core/hosts/nuke/api/plugin.py
Port of https://github.com/ynput/OpenPype/pull/6211
=> Nuke: expose knobs backward compatibility fix - OP-8164

client/ayon_core/hosts/aftereffects/plugins/create/create_render.py, client/ayon_core/hosts/nuke/api/plugin.py, client/ayon_core/hosts/photoshop/plugins/create/create_image.py, client/ayon_core/lib/applications.py, client/ayon_core/lib/transcoding.py, client/ayon_core/pipeline/colorspace.py, client/ayon_core/pipeline/context_tools.py, client/ayon_core/pipeline/create/legacy_create.py, client/ayon_core/pipeline/create/subset_name.py, client/ayon_core/pipeline/load/plugins.py, client/ayon_core/pipeline/project_folders.py, client/ayon_core/pipeline/publish/lib.py, client/ayon_core/pipeline/version_start.py, client/ayon_core/pipeline/workfile/lock_workfile.py, client/ayon_core/pipeline/workfile/path_resolving.py, client/ayon_core/plugins/publish/cleanup.py, client/ayon_core/plugins/publish/collect_comment.py, client/ayon_core/plugins/publish/extract_burnin.py, client/ayon_core/plugins/publish/extract_color_transcode.py, client/ayon_core/plugins/publish/extract_review.py, client/ayon_core/plugins/publish/extract_thumbnail.py, client/ayon_core/plugins/publish/integrate_product_group.py, client/ayon_core/settings/ayon_settings.py, client/ayon_core/tools/creator/window.py, client/ayon_core/tools/pyblish_pype/control.py
Core project settings conversion was removed.
Replace `"global"` with `"core"` and moved conversions into the code.
Things that should be validated.
=> Core: Use AYON settings

client/ayon_core/hosts/nuke/plugins/publish/validate_exposed_knobs.py
Port of https://github.com/ynput/OpenPype/pull/6213
=> Nuke: openpype expose knobs validator - OP-8166

client/ayon_core/host/dirmap.py, client/ayon_core/lib/applications.py, client/ayon_core/lib/ayon_info.py, client/ayon_core/pipeline/anatomy.py, client/ayon_core/settings/__init__.py, client/ayon_core/settings/lib.py, client/ayon_core/tools/experimental_tools/tools_def.py
Removed `get_local_settings` function from `ayon_core.settings`.
Local settings are not implemented in AYON the same way as were in OpenPype. Some of the local settings from OpenPype are at this moment not available in AYON at all, and other ones are stored per addon. It is not possible to easily receive all the values as it was in OpenPype, at least not now, and we have to make full replacement of them in future.
There is no visible change.
=> Chore: Remove local settings function

create_package.py
If you use `create_package.py` to make a core addon package, it goes straight to the `docker/addons` folder. This way, you don't have to stress about deleting any addons that are already there.
1. use following cmd and notice that addons in your ayon-docker/addon folder are not removed.
```
cd [YOUR ayon-core repo dir]
python ./create_package.py --skip-zip --output [ayon-docker repo folder path]/addons
```
=> Chore: stop removing addons via create package py 

client/ayon_core/modules/job_queue/__init__.py, client/ayon_core/modules/job_queue/addon.py, client/ayon_core/modules/job_queue/module.py
Conversion of JobQueue addon to inherit from AYONAddon.
The addon does not have AYON addon variant now and there is change that will be fully removed with first release of AYON-core.
The addon does not have any current usage so it is no way to really test.
=> Job queue addon uses AYONAddon

client/ayon_core/hosts/houdini/api/plugin.py, client/ayon_core/hosts/houdini/plugins/create/create_workfile.py, client/ayon_core/hosts/houdini/plugins/publish/validate_subset_name.py
A separate PR for dealing with Houdini for https://github.com/ynput/ayon-core/pull/113 
The new `productName` Key conflicts with `Karma ROP`. 
So, instead we are going to use `AYONProductName` 
The caveat is using  `AYONProductName`  when creating instances but reading its value as `productName` when collecting instances.
I don't sure if we should provide a convert legacy code in this PR.
From the main PR:
- Open Houdini and try all create plugin and publish. Validated output if can be loaded.
- Open Houdini with workfile that does have instances before this PR and publish them.
=> Houdini: use product name n product type (follow up PR)

client/ayon_core/hosts/maya/plugins/publish/collect_render.py, client/ayon_core/modules/timers_manager/plugins/publish/start_timer.py, client/ayon_core/modules/timers_manager/plugins/publish/stop_timer.py
Fixed places where subkey `"modules"` from system settings was used.
I'm not sure if maya should know how to get royal render root, but that's question for a different PR.
1. Launch of application should not crash because of missing `"modules"` key in system settings
=> Don't use "modules" subkey in system settings

.github/workflows/issue_to_clickup_trigger.yml
- Added a trigger workflow to sync GitHub issues with ClickUp
- Triggered by manual dispatch or labeled issue event
=> Add trigger workflow to sync issues with ClickUp

client/ayon_core/plugins/publish/collect_audio.py
Added missing hosts (Blender, Houdini and Max) to `collect_audio`.
1. Load an audio file.
2. Try publishing a review. It should include the audio file.
=> Added missing hosts to collect_audio

client/ayon_core/hosts/max/plugins/create/create_workfile.py
Removing `remove instances` function in 3dsmax workfile creator
It does not make sense to remove workfile instance created with auto creator.
1. Launch Max
2. Create Workfile
3. removing instances should be gone.
=> 3dsMax: Remove workfile instance is not possible

client/ayon_core/tools/workfiles/control.py
Fix copy and open published workfiles.
The button just saved as current workfile instead of using the representation path.
1. Make sure a workfile is published.
2. Launch the host/dcc.
3. Open workfiles tool.
4. Check `Published workfile` checkbox.
5. Select published workfile and click `Copy & Open` button.
6. It should copy and open the file.
=> Workfiles tool: Copy and open of published workfile works

client/ayon_core/hosts/max/plugins/publish/validate_model_name.py
In AYON, there is no `instance.context.data["subset"]`. This PR is to replace the use of this with instance name on validate model name
n/a
1. Launch Max
2. Create Model Instance
3. Enable `Validate Model Name`
4. It should validate subset correctly if the validation regex sets to subset-related param.
=> Max: Use instance.data["productName"] instead of instance.context.data["subset"] in validate model name

client/ayon_core/hosts/max/api/preview_animation.py, client/ayon_core/hosts/max/plugins/publish/validate_extended_viewport.py
Retaining 3dsMax Viewport layout and checking for non-extended viewport for preview
Previously, when doing a preview in 3ds max, the top left viewport would always be changed to the review camera view.
Even if it is a non camera view. Like a top or a right view.
It also doesn't like it if the top left viewport is an extended viewport (like a redshift renderview)
If another viewport (not the top left) is an extended viewport, the process of switching layouts remove all extended viewports.
Instead of switching layouts and switching back, we maximize the first non-extended viewport to do the review.
We store the camera as well as the type and switch it back to it's original camera or type when the preview is done.
We then un-maximize it if we had to maximize it before.
Added a validator to …
=> 3dsMax: Retaining Viewport Layout during Preview

client/ayon_core/hosts/maya/plugins/publish/collect_inputs.py
Collect inputs errors out during maya deadline submission as it can't get the name of renderlayer.
This PR is to help to find the name of the renderlayer.
Links to https://github.com/ynput/ayon-core/pull/173
If you want to test the code, you need to somehow resolve the code above first.
1. Create Render Instance in Maya
2. Publish
=> Maya: bug fix the invalid renderlayer name errors out in collect inputs

client/ayon_core/pipeline/create/context.py
Handled case when `task_entity` in `create` method is `None`.
1. Create object of `CreateContext` and run `create` method without task entity.
2. It should not crash because of missing `task_name` variable.
=> Create: Add missing variable 'task_name'

client/ayon_core/hosts/tvpaint/plugins/load/load_reference_image.py
Removed redundant logic which was broken anyway, call to `get_representation_context` had wrong arguments
Note: Arguments passed to `get_representation_context` were wrong because it also takes `project_name` as argument
1. Update Reference Image in TVPaint should work
=> TVPaint: Fix Load Reference Image Update logic

client/ayon_core/tools/sceneinventory/switch_dialog/dialog.py
Fix `fields` for getting last versions.
Should fix this error:
```python
```
Reported on [discord](https://discord.com/channels/517362899170230292/517382145552154634/1219774549394981005)
1. Switch Folder dialog should work
2. No errors should be logged or printed.
=> Bugfix: Switch Folder dialog, fix `fields` for getting last versions

client/ayon_core/hosts/maya/plugins/load/load_vrayproxy.py
- Fix refactored import so function call is correct.
Otherwise the error is:
```python
During load error happened on Product: "modelMain" Representation: "abc" Version: 29
Error message: name 'ayon_api' is not defined
File "E:\dev\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
load_with_repre_context(
File "E:\dev\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
return loader.load(repre_context, name, namespace, options)
File "E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_vrayproxy.py", line 55, in load
filename = self._get_abc(
File "E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_vrayproxy.py", line 192, in _get_abc
abc_rep …
```
=> Bugfix: Maya Load Vray Proxy fix import

client/ayon_core/hosts/blender/plugins/publish/validate_file_saved.py
Tweak clarity of the message that is about the workfile being unsaved… - not being 'empty'.
n/a
1. Publish from Blender, do not save - hit the validation error
2. Message should be understandable by artists
=> Blender: Improve Validate Workfile Saved message 

client/ayon_core/lib/ayon_connection.py
Monkey patch ayon api functions to fix issue with get last verisons.
Last versions getter are also returning hero version which lead to invalid resolving of latest version. This will be fixed in next release of ayon python api but until that point the methods are monkey patched ([ayon-api PR](https://github.com/ynput/ayon-python-api/pull/129)).
1. Scene inventory should show correctly latest version if there is hero version.
=> Chore: Fix last versions getters for ayon api

client/ayon_core/hosts/blender/plugins/publish/validate_transform_zero.py
Validate Transform Zero report + repair improve validation report + add repair actionpair action
n/a
1. Publish model with transforms on objects
2. Validation report should be clear
3. Repair action should work
=> Blender: Validate Transform Zero report + repair

client/ayon_core/cli_commands.py
The imports of openpype.tools.utils.host_tools.__init__.py were throwing an error due to trying to import QtWidgets unnecessarily.
> [!NOTE]
> This is port of community PR to OpenPype - https://github.com/ynput/OpenPype/pull/6205
1. Run a headless publish in a farm worker that doesn't have libGL
=> Core: Headless publish failing without GL lib

client/ayon_core/tools/workfiles/models/workfiles.py
Workfiles tool uses anatomy templates correctly.
The issue was caused by https://github.com/ynput/ayon-core/pull/190 . It did use template string when it should use object and opposite. Added few docstrings and comments.
1. Workfiles tool is able to save workfile (e.g. using Save As button).
=> Workfiles tool: Fix work with anatomy templates

client/ayon_core/hosts/maya/plugins/publish/validate_rig_contents.py
Fix geometry validation for rig validator
It was not returning the invalid nodes, so returned None always.
Also - fixed the docstrings.
1. Rig validation of geometry node types should work as intended.
=> Bugfix: Maya validate rig contents geometry actually return invalid nodes

client/ayon_core/hosts/maya/plugins/publish/validate_look_shading_group.py
Fix Validate Look Shading Group syntax error.
n/a
1. Plugin should not be listed as crashed plug-in
2. Plugin should work.
=> Maya: Validate Look Shading Group syntax error

client/ayon_core/plugins/publish/extract_color_transcode.py
This PR simply adds `new_repre["outputName"] = output_name` inside the `_rename_in_representation` function.
Without this if a user would like to add eg {colorspace} to a name preset it wouldn't be found, so you can't have two oiio outputs as the second one would try and overwrite the first publish.
This bug was found by @jakubjezek001 under the hackinton but I'm submitting it as we fixed in on my ayon instance.
1. add <_{colorspace}> to your render name preset
2. add two oiio conversion presets
3. publish a render
Without this fix you'll get an error that it can't publish an already published product. With the fix + _{colorspace} added to the name Ayon will be able to publish the new oiio products with new correct output names.
=> Re-add outputName to _rename_in_representation

client/ayon_core/hosts/maya/plugins/publish/validate_animation_out_set_related_node_ids.py, client/ayon_core/hosts/maya/plugins/publish/validate_arnold_scene_source_cbid.py, client/ayon_core/hosts/maya/plugins/publish/validate_look_id_reference_edits.py, client/ayon_core/hosts/maya/plugins/publish/validate_node_ids.py, client/ayon_core/hosts/maya/plugins/publish/validate_node_ids_deformed_shapes.py, client/ayon_core/hosts/maya/plugins/publish/validate_node_ids_in_database.py, client/ayon_core/hosts/maya/plugins/publish/validate_node_ids_related.py, client/ayon_core/hosts/maya/plugins/publish/validate_node_ids_unique.py, client/ayon_core/hosts/maya/plugins/publish/validate_rig_out_set_node_ids.py, client/ayon_core/hosts/maya/plugins/publish/validate_rig_output_ids.py, server_addon/maya/server/settings/main.py, server_addon/maya/server/version.py
Add a single setting to disable the `cbId` workflow **validations** in Maya.
This is an equivalent to [this commit](https://github.com/BigRoy/OpenPype/commit/9a543e9fffc1bb3ea58a22b95efaccfb2f6b8632) that we did to disable `cbId` validations in Maya in our USD project.
Implemented because you might want to disable `cbId` completely when moving to USD since it's layering can replace the full `cbId` workflow for looks, etc. Also relevant to this [Ynput discord discussion](https://discord.com/channels/517362899170230292/1219996539146076160/1220057378808922173) with Lucas Bruchhage at BCN Visuals.
This can benefit from a follow up PR that will, using the same toggle, disable the `cbId` creation on file save completely. However - removing that completely might be hard with certain other areas …
=> Maya: Add setting to disable `cbId` workflow

client/ayon_core/hosts/maya/tools/mayalookassigner/widgets.py
Use correct key to access folder entity in tool code.
1. Tool can be operational.
=> Maya: Look assigner fix folder entity key

client/ayon_core/hosts/maya/plugins/load/load_redshift_proxy.py, client/ayon_core/hosts/maya/plugins/load/load_reference.py, client/ayon_core/hosts/maya/plugins/load/load_vdb_to_arnold.py, client/ayon_core/hosts/maya/plugins/load/load_vdb_to_redshift.py, client/ayon_core/hosts/maya/plugins/load/load_vdb_to_vray.py, client/ayon_core/hosts/maya/plugins/load/load_vrayproxy.py, client/ayon_core/hosts/maya/plugins/load/load_vrayscene.py, client/ayon_core/hosts/maya/plugins/load/load_yeti_cache.py, client/ayon_core/hosts/unreal/plugins/load/load_alembic_animation.py, client/ayon_core/hosts/unreal/plugins/load/load_layout.py, client/ayon_core/hosts/unreal/plugins/load/load_layout_existing.py
Load plugins are looking for product type on product entity instead of context data.
Key `"family"` may not available on representation context as we've changed it to product type.
1. Load plugins can be used on newest published instances from current develop.
EDITED:
The same fix was also done for Unreal plugins.
=> Maya: Load plugins use correct source for product type

client/ayon_core/hosts/houdini/plugins/publish/collect_karma_rop.py, client/ayon_core/hosts/houdini/plugins/publish/collect_mantra_rop.py
Fix indendations
These would've broken in the case the "chunkSize" parm did not exist because `render_products` and `files_by_aov` would have been undefined variables.
1. Publish Karma ROP instance
2. Publish Mantra ROP instance
(Also test instances without the `chunkSize` parm, likely from older legacy instances - but maybe best to reproduce by removing the parms manually?)
=> Bugfix: Houdini Karma/Mantra collectors wrong indentation

client/ayon_core/hosts/houdini/plugins/load/load_camera.py
Camera loader allow switching folders/products via scene inventory (manage).
Also removed redundant comment.
1. Switch folder should work for Camera loader in Houdini
=> Houdini: Camera loader allow switching folders/products

client/ayon_core/modules/launcher_action.py
Remove backwards compatibility for `AVALON_ACTIONS` 
n/a
1. Launcher + launcher actions should work as usual
=> Remove deprecated `AVALON_ACTIONS`

client/ayon_core/pipeline/colorspace.py
Fix colorspace `get_remapped_colorspace_to_native` and `get_remapped_colorspace_from_native`
n/a
1. Use API methods of `get_remapped_colorspace_to_native` and `get_remapped_colorspace_from_native` in any way.
=> Fix initial state for `CachedData.remapping`

server_addon/maya/server/settings/publishers.py
Settings for Maya Extract Camera "bake attributes" should now be labeled correctly and have a description.
I did not bump the server addon version because it's cosmetics only for the settings. So it's fine it only starts showing in future releases.
1. Settings for Maya Extract Camera "bake attributes" should now be labeled correctly and have a description.
=> Maya Settings: Extract Camera bake attributes title fix + add description

client/ayon_core/hosts/maya/plugins/create/create_unreal_skeletalmesh.py, client/ayon_core/hosts/maya/plugins/create/create_unreal_staticmesh.py
Remove apply settings logic for Create unreal product types.
No need to define `apply_settings` since it gets auto-applied. 
n/a
1. Settings for Create Unreal Skeletal Mesh and Create Unreal Static Mesh should still work
=> Maya: Remove apply settings logic for Create unreal product types

client/ayon_core/hosts/maya/plugins/create/create_unreal_yeticache.py
Make Creator class name compared to existing `CreateYetiCache` in `create_yeti_cache.py`
n/a
1. Publishing for Create Yeti Cache and Create Unreal Yeti Cache should both work.
2. Legacy instances for Unreal Yeti Cache should continue to work.
=> Maya: Make Create Unreal Yeti Cache creator class name unique `

client/ayon_core/hosts/maya/plugins/create/convert_legacy.py
Use correct variable `product_type` instead of `family` in maya legacy convertor plugin.
=> Maya: Fix variable name in convertor plugin

client/ayon_core/hosts/harmony/plugins/create/create_farm_render.py, client/ayon_core/hosts/harmony/plugins/publish/collect_scene.py, client/ayon_core/hosts/hiero/api/otio/hiero_import.py, client/ayon_core/hosts/hiero/api/plugin.py, client/ayon_core/hosts/hiero/api/startup/Python/StartupUI/PimpMySpreadsheet.py, client/ayon_core/hosts/hiero/api/startup/Python/StartupUI/otioimporter/OTIOImport.py, client/ayon_core/hosts/hiero/api/tags.py, client/ayon_core/hosts/hiero/plugins/publish/precollect_instances.py, client/ayon_core/hosts/hiero/plugins/publish_old_workflow/precollect_retime.py, client/ayon_core/hosts/houdini/plugins/load/load_alembic.py, client/ayon_core/hosts/houdini/plugins/publish/validate_cop_output_node.py, client/ayon_core/hosts/max/plugins/publish/validate_renderpasses.py, client/ayon_core/hosts/maya/api/lib.py, client/ayon_core/hosts/maya/plugins/publish/collect_render.py, client/ayon_core/hosts/maya/plugins/publish/extract_unreal_skeletalmesh_fbx.py, client/ayon_core/hosts/maya/tools/mayalookassigner/models.py, client/ayon_core/hosts/tvpaint/plugins/create/create_render.py, client/ayon_core/hosts/unreal/lib.py, client/ayon_core/hosts/unreal/plugins/create/create_render.py, client/ayon_core/modules/deadline/plugins/publish/submit_maya_deadline.py, server_addon/create_ayon_addons.py
Small enhancements of code formatting.
Removed unused variables. Removed unnecessary f-strings, removed `format` when there is nothing to format, fixed some formattings which used combination of `{}` and `%s` for formatting. Fixed one Python 2 exception capture (`except Exception, e` > `except Exception as e`). Use `isinstance` for type check. Converted lambda to real function.
NOTE: Based on PR https://github.com/ynput/ayon-core/pull/196 .
=> Chore: Formatting fixes

client/ayon_core/hosts/tvpaint/plugins/create/create_render.py
Semi-automated create plugin did not change group name when actually should which may lead to invalid render layer name.
1. Make sure you're using code from this PR.
2. Run create plugin that automatically detects render layers and passes in scene.
3. Color groups in TVPaint should be renamed to correct group name.
NOTE: Based on PR https://github.com/ynput/ayon-core/pull/196 .
=> TVPaint: Fix george script in auto create plugin

client/ayon_core/hosts/houdini/api/creator_node_shelves.py
Fix creating instances via TAB menu in Houdini
Error:
```python
File "ayon_create.io.openpype.creators.houdini.vdbcache", line 3, in <module>
File "E:\dev\ayon-core\client\ayon_core\hosts\houdini\api\creator_node_shelves.py", line 97, in create_interactive
folder_entity = ayon_api.get_folder_by_path(
File "C:\Program Files\Ynput\AYON 1.0.2\dependencies\ayon_api\_api.py", line 810, in get_folder_by_path
return con.get_folder_by_path(*args, **kwargs)
File "C:\Program Files\Ynput\AYON 1.0.2\dependencies\ayon_api\server_api.py", line 3799, in get_folder_by_path
for folder in folders:
File "C:\Program Files\Ynput\AYON 1.0.2\dependencies\ayon_api\server_api.py", line 3721, in get_folders
for parsed_data in query.continuous_query(self):
File "C:\Program …
```
=> Houdini: Fix creating instances from tab menu

client/ayon_core/modules/clockify/launcher_actions/ClockifyStart.py, client/ayon_core/modules/clockify/launcher_actions/ClockifySync.py, client/ayon_core/pipeline/actions.py, client/ayon_core/plugins/actions/open_file_explorer.py, client/ayon_core/tools/launcher/models/actions.py
Prepared selection object that helps to handle selection in Launcher actions.
The object should backwards compatible for unconverted actions.
1. Launcher actions are working (e.g. applications)
2. It would be nice to test backwards compatibility of uncorverted actions but I don't have any.
=> Launcher: Use selection object for action

client/ayon_core/plugins/publish/help/validate_containers.xml
Rename `Options` to `Context` in report
It has been `Context` for a while now.
1. Outdated containers message should now state "Context" instead of "Options"
=> Validate Containers: Rename `Options` to `Context` in report

client/ayon_core/hosts/blender/plugins/publish/validate_mesh_no_negative_scale.py, client/ayon_core/hosts/celaction/plugins/publish/collect_celaction_cli_kwargs.py, client/ayon_core/hosts/maya/plugins/publish/validate_color_sets.py, client/ayon_core/hosts/maya/plugins/publish/validate_mesh_ngons.py, client/ayon_core/hosts/maya/plugins/publish/validate_mesh_no_negative_scale.py, client/ayon_core/hosts/maya/plugins/publish/validate_mesh_non_manifold.py, client/ayon_core/hosts/maya/plugins/publish/validate_mesh_normals_unlocked.py, client/ayon_core/hosts/maya/plugins/publish/validate_no_animation.py, client/ayon_core/hosts/maya/plugins/publish/validate_shape_render_stats.py, client/ayon_core/hosts/maya/plugins/publish/validate_shape_zero.py, client/ayon_core/hosts/maya/plugins/publish/validate_transform_zero.py, client/ayon_core/hosts/maya/plugins/publish/validate_unique_names.py, client/ayon_core/hosts/maya/plugins/publish/validate_yeti_rig_input_in_instance.py, client/ayon_core/hosts/nuke/plugins/publish/extract_script_save.py, client/ayon_core/hosts/tvpaint/plugins/publish/extract_sequence.py
Use explicit plug-ins from pyblish api instead of legacy plug-ins
Use explicit pyblish api orders, instead of order of legacy plug-ins
This shouldn't change usage behavior but these are more explicit and by refactoring these older uses we're now making it more unified usage inside AYON by removing the legacy usage.
Only remaining usage seems to be in [`./tools/pyblish_pype/mock.py` here](https://github.com/ynput/ayon-core/blob/a4f2f76fbf98becd22b75012abf1abfc09bbd69d/client/ayon_core/tools/pyblish_pype/mock.py)
1. Changed plug-ins should still work
=> Chore: Use explicit plug-ins and orders from pyblish api instead of legacy plug-ins

client/ayon_core/hosts/maya/plugins/publish/validate_shape_render_stats.py
Improve validation message for Maya's Validate Shape Render Stats
Now raises `PublishValidationError`
Also removes Py2 fallback logic with `iteritems`.
Validator is disabled by default, enable `ayon+settings://maya/publish/ValidateShapeRenderStats`
1. Publish model with non-default render stats
2. See validation report - should be much improved.
=> Maya: Validate Shape Render Stats improve error message

client/ayon_core/hosts/maya/plugins/publish/validate_transform_zero.py
Tweak validate transform zero artist report formatting.
- Add line break before first object name
- Add static description instead of listing objects right-hand side.
1. Enable `ValidateTransformZero` plugin in settings
2. Publish model with transforms
2. Validation should be clear.
=> Maya: Tweak validate transform zero formatting

client/ayon_core/hosts/maya/plugins/publish/help/validate_animation_out_set_related_node_ids.xml, client/ayon_core/hosts/maya/plugins/publish/validate_animation_out_set_related_node_ids.py
Validate Animation Out Set Related Node Ids improve validation report message.
Note that it does have some additional changes:
- Ignore nodes without ids - that is validated elsewhere
- Only check specific types instead of excluding only locators (so that e.g. also constraints or deformers are excluded in the check)
- Improve report message
n/a
1. Loaded rigs (referenced) with additional deformers applied should work to publish animation for.
2. Validator should work and be clear in messaging.
=> Maya: Validate Animation Out Set Related Node Ids improve report

client/ayon_core/hosts/maya/api/customize.py
When opening Maya - and opening the Look Assign tool via the toolbox the window was not parented to Maya main window. And as such, clicking somewhere inside of maya would make the dialog appear behind maya - which is very annoying.
This PR makes the behavior the same as when Look Assigner is opened via AYON top menu - parented to the Maya main window.
Note that both buttons (toolbox and in menu) use the same 'singleton' dialog. So as soon as you had run it from AYON menu once in current session then opening via toolbox again would still have it parented to Maya. Vice-versa the same, if first opened via Toolbox and then via AYON menu it would still _not_ be parented to maya windows.
1. Launch Maya
2. Open Look Assigner via Maya Toolbox
3. Look assigner tool should be parented to maya main …
=> Maya: Parent look assigner UI to Maya window when opening via toolbox

client/ayon_core/hosts/maya/plugins/publish/validate_look_shading_group.py
Do not error with confusing message if shadingEngine has no material for whatever reason.
We hit this in production once and took a few minutes to debug and find the issue. By having this warning it's much easier to find what might be causing the issue.
1. Prepare a look
2. For one material, break the connection between material and `shadingEngine.surfaceShader`
3. Publish look
4. Validator should detect it without crashing.
=> Maya: Validate Look Shading Group ignore if no material

client/ayon_core/hosts/maya/api/action.py
Support `SelectInvalidAction` with pyblish ContextPlugin
I don't believe there's currently any `ContextPlugin` in the maya integration that is actively using the `SelectInvalidAction`. However we had some in our codebase and it would be nice to port at least this functionality upstream to avoid any surprises in the future.
We might want to match the logic in other host integrations if they also have a `SelectInvalidAction` so they are also prepared.
1. Select Invalid actions should still work in publisher UI.
=> Maya: Support SelectInvalidAction with pyblish ContextPlugin

client/ayon_core/hosts/houdini/api/pipeline.py
Fix removal of `get_id_required_nodes` and `generate_ids`
Likely one of the many PRs today introduced a merge conflict that got resolved the wrong way.
Should originally have been removed by https://github.com/ynput/ayon-core/pull/263
1. Workfile save in Houdini should work without errors.
=> Houdini: Fix removal of `get_id_required_nodes` and `generate_ids`

client/ayon_core/hosts/maya/plugins/publish/extract_gpu_cache.py, server_addon/maya/server/settings/publishers.py, server_addon/maya/server/version.py
Add support for changing the `enabled`, `active` and `optional` state in settings of:
- Extract GPU Cache
- Extract Model (Maya Scene)
n/a
1. Default values for the settings should be 'backwards compatible' (behave like before)
2. Changing settings for Extract GPU Cache should work
3. Changing settings for Extract Model (Maya Scene) should work
=> Maya: ExtractGpuCache and ExtractModel (maya scene) optional state in settings

client/ayon_core/plugins/publish/extract_review.py
Cleanup code: remove unused variable `pixel_aspect` and fix typos
n/a
1. Extract review should work.
=> Extract Review: Fix typos + remove unused variable

client/ayon_core/hosts/maya/api/lib.py, client/ayon_core/hosts/maya/tools/mayalookassigner/vray_proxies.py
- Use the result from `get_last_versions` directly because it's already by product id.
- List looks based on product type instead of matching by name
- Query once instead of twice per look assignment (json + ma repre in one call)
- Change default argument values to `lookMain` insteaf of `lookDefault`
n/a
1. Listing looks in Look Assigner tool should still work
2. Look assignments should still work
=> Maya: Optimize look logic

client/ayon_core/plugins/publish/extract_burnin.py
Opt-out earlier if no burnins per representation to process
This is a tiny optimization.
But mostly this reduces logging for instances that do not have any burnins to process.
1. Extract Burnin should still work
=> Extract Burnin: Do not prepare burnin data if no burnins for representations

client/ayon_core/hosts/substancepainter/plugins/load/load_mesh.py
Substance Painter: Allow loading `usd` mesh to substance painter
n/a
1. Load mesh in loader should now also show (and work) for USD representations.
=> Substance Painter: Allow loading `usd` mesh to substance painter

client/ayon_core/plugins/publish/integrate_hero_version.py
The `IntegrateHeroVersion` plugin was not properly checking whether it should run.
1. Enable hero integration in settings.
2. Setup `model` in Maya and uncheck `Integrate Hero Version`.
3. Verify that `Integrate Hero Version` does not run.
=> Use is_active for proper optional functionality in hero integration.

client/ayon_core/hosts/nuke/api/plugin.py, client/ayon_core/plugins/publish/extract_review.py
Use `reformatted` tag name instead of `reformated`.
The only place which is using the tag was modified to be backwards compatible. @jakubjezek001 do you think it is necessary? Do we know about other places using the tag?
NOTE: Based on PR https://github.com/ynput/ayon-core/pull/196 .
=> Chore: Tag 'reformatted' typo fix

client/ayon_core/hosts/maya/api/lib.py
A bug fix for the issue reported here https://github.com/ynput/ayon-core/pull/323#pullrequestreview-1970044683
Frame Range values should be taken from task level attributes. 
1. Launch Maya 
2. Reset Frame Range
=> Maya: Use frame range from task attributes

server_addon/blender/server/settings/main.py, server_addon/blender/server/settings/publish_plugins.py, server_addon/celaction/server/settings.py, server_addon/flame/server/settings/create_plugins.py, server_addon/flame/server/settings/main.py, server_addon/flame/server/settings/publish_plugins.py, server_addon/hiero/server/settings/loader_plugins.py, server_addon/hiero/server/settings/main.py, server_addon/hiero/server/settings/publish_plugins.py, server_addon/nuke/server/settings/loader_plugins.py, server_addon/nuke/server/settings/main.py, server_addon/nuke/server/settings/publish_plugins.py, server_addon/resolve/server/settings.py
Fix class name typos `Pugin` to `Plugin` in settings.
Since this does not change the field names this shouldn't actually influence the stored settings - right? @iLLiCiTiT @martastain
If so, I wouldn't bother bumping server addon versions either.
1. Settings should still work
=> Settings: Fix class name typos `Pugin` to `Plugin`

client/ayon_core/hosts/fusion/api/lib.py, client/ayon_core/hosts/harmony/api/pipeline.py, client/ayon_core/hosts/houdini/api/lib.py, client/ayon_core/hosts/houdini/plugins/inventory/set_camera_resolution.py, client/ayon_core/hosts/max/api/lib.py, client/ayon_core/hosts/max/api/lib_rendersettings.py, client/ayon_core/hosts/maya/api/lib.py, client/ayon_core/hosts/maya/api/lib_rendersettings.py, client/ayon_core/hosts/maya/plugins/publish/validate_maya_units.py, client/ayon_core/hosts/unreal/plugins/load/load_animation.py, client/ayon_core/hosts/unreal/plugins/load/load_layout.py, client/ayon_core/pipeline/context_tools.py
Use more suitable function name to get current folder entity and added function to get current task entity.
The function `get_current_folder_entity` was intended to be also used to get different folder from current project, but it not used that way so that part was removed, which gave option to use more suitable name of the function.
Current task entity funcion is not trivial and must call twice to get the task entity, that might change with new ayon api.
1. Validate my reasoning is correct.
2. All usage of the function should be replaced.
=> Chore: Better context entity getter function

client/ayon_core/addons/applications/ayon_applications/addon.py
Disable applications addon if does not have available settings (addon is disabled on server).
The client addon would crash if server would be disabled.
=> Applications: Disable applications addon if does not have settings available

client/ayon_core/plugins/publish/extract_burnin.py
Add `--headless` flag to execution of burnin script from **Extract Burnins** to prevent any UI interaction.
This is fixing the issue where in certain cases **Extract Burnins** could pop some update windows or similar. Oh, and also fixing some typos.
It could be tested in cases where running launcher would cause update for example.
=> Bug: add `headless` flag to prevent UI interactivity in burnins extraction

client/ayon_core/hosts/maya/api/lib.py
Don't set time slider values one by one, but set all at once.
Less maya calls is always good.
This really shouldn't break anything. :)
1. Updating scene frame range should work. (e.g. reset frame range) or by the 'fix' in the prompt on scene save if your scene is wrong frame range.
=> Maya: Set scene frame range - apply playback options in one call

client/ayon_core/hosts/maya/plugins/load/load_rendersetup.py
Maya Load Rendersetup with more options:
- allow loading unmanaged 
- automatically 'accept' the import 
- pick import mode
n/a
1. Loading RenderSetup to maya should work.
=> Maya: Load RenderSetup add more options

client/ayon_core/hosts/maya/api/lib.py
Optimize `get_related_sets` by opting-out earlier if no valid sets to perform less maya calls
This is a bit of a micro-optimization. Just happened to have this in our OpenPype codebase.
1. Maya look collecting and publishing should still work
=> Maya: Optimize `get_related_sets`

client/ayon_core/hosts/maya/api/lib.py, client/ayon_core/hosts/maya/plugins/publish/collect_arnold_scene_source.py, client/ayon_core/hosts/maya/plugins/publish/collect_instances.py, client/ayon_core/hosts/maya/tools/mayalookassigner/commands.py
Optimize `get_all_children` logic with ignoring intermediate objects
n/a
1. Publishing should still work (with regards to `Collect Instances` plugin) so really any one of them, but test e.g. model, pointcache and rigs
2. Maya Look assigner should still work
3. Publishing arnold standins (`ass` product type) should still work
=> Maya: Optimize `get_all_children` logic with ignoring intermediate objects

client/ayon_core/tools/workfiles/control.py
Context change is propagated correctly, because controller of workfiles tool does capture it correctly.
Change the context also in controller, and unify the context change into single method. Removed `reset` of controller on save as ( I'm not sure why the reset was there, probably only to update current context?).
1. Launch DCC -> Task 1.
2. Open workfiles tool.
3. Keep folder, and change task and open workfile. Must be `Open` not `Save as`. -> Task 2
4. Check current context in AYON menu
5. Open workfiles tool again.
6. Again keep folder, change task back to the first one. -> Task 1
7. Context in AYON menu should show context of Task 2
1. Workfile opened in same folder, but different task will change the context.
Resolves https://github.com/ynput/ayon-core/issues/180
=> Workfiles tool: Fix update of context change

client/ayon_core/hosts/maya/plugins/create/create_render.py
Provide better descriptive message on the creation failure when trying to create another "render" instance.
The render instance acts as a Singleton instance. When present all renderlayers in the scene are detected as renderable instances - this might not be clear for newcomers at first and they may expect that clicking Create again will in fact create more Render Setup layers. This improved message provides better guidance to new artists
Before:
After:
1. Create a render instance.
2. Create it again. (You'll get the error message)
=> Maya: Create multiple "render" instances better error message

client/ayon_core/hosts/maya/plugins/publish/validate_node_ids_unique.py
Improve logs and readability of the report for unique node id validation.
n/a
1. Nodes with the same `cbId` should be reported better in the validation report.
=> Maya: Improve validate node ids unique report

client/ayon_core/hosts/maya/plugins/publish/validate_node_ids_in_database.py
For the Validate Node Ids In Database validator cache the folder ids of the project on the first query so we don't need to query all folder ids in the current project per instance.
Also only query the database if the instance actually contains nodes that should have an id to begin with.
1. Validation of whether folder id in `cbId` (part before the `:`) is a valid folder id in current project should still work.
2. It should be faster for many instances.
=> Maya: Validate node ids in database, query folder ids once

client/ayon_core/hosts/maya/plugins/publish/collect_file_dependencies.py
Only collect file dependencies if enabled in settings and only collect if renderlayer family is present
Now also excludes "duplicate" entries.
Still has the issue that it doesn't work correctly for all udim tiles, etc. The logic is just too simple for that and I believe has been reported before. Anyway, for now this is a good optimization.
The setting is `deadline > publish > MayaSubmitDeadline > asset_dependencies `
1. Collect file dependencies should only run if a renderlayer instance is active.
2. When enabled in settings, file dependencies should be collected and submitted along to Deadline job
3. When disabled in settings, file dependencies should not be collected
=> Maya: Optimize collect file dependencies

client/ayon_core/hosts/maya/api/workfile_template_builder.py
When builder a template with `renderSetup` product, this error would occur since `renderSetup` product now does not return any roots after https://github.com/ynput/ayon-core/pull/310;
```
```
1. Setup placeholder with `renderSetup` product in Maya.
2. Build the templated workfile.
=> Maya: Account for no nodes in container

client/ayon_core/hosts/hiero/plugins/publish/extract_thumbnail.py, client/ayon_core/modules/deadline/plugins/publish/submit_publish_cache_job.py, client/ayon_core/modules/deadline/plugins/publish/submit_publish_job.py, client/ayon_core/modules/royalrender/plugins/publish/create_publish_royalrender_job.py
This fixes a long standing issue where the env var used to set the user to login as in Shotgrid in Deadline wasn't being passed, as reported here https://community.ynput.io/t/shotgrid-integration-addon/63/42
1. Submit a Shotgrid publish job to Deadline
=> Fix AYON shotgrid username passed to Deadline

client/ayon_core/hosts/houdini/plugins/publish/collect_local_render_instances.py, client/ayon_core/hosts/houdini/plugins/publish/collect_review_data.py, client/ayon_core/hosts/houdini/plugins/publish/extract_opengl.py, client/ayon_core/hosts/houdini/plugins/publish/validate_review_colorspace.py, client/ayon_core/hosts/houdini/plugins/publish/validate_scene_review.py
support adding review family to the render
Follow up to https://github.com/ynput/ayon-core/pull/328
I'm not sure about my idea to add review family to render.
So, I made it here in a separate PR.
1. on testing https://github.com/ynput/ayon-core/pull/328
2. create a a render instance and select `"Local machine rendering"` or `"Use existing frames (local)"`
3. Published render should include a `mp4` file with burnins. 
https://github.com/ynput/ayon-core/assets/20871534/f825205e-8073-4244-b0c5-240402c650d0
=> Houdini local render: support adding review family to the render

client/ayon_core/plugins/load/delivery.py
Fix delivery action after recent refactoring of ayon core.
Fixes #351 
Since directory and file is now separate in the delivery templates I've also made them two labels in the delivery UI for better clarity as to what is what.
1. Set up a delivery template in Anatomy settings `ayon+anatomy://PROJECTNAME/templates/delivery`, for example like these examples:
```json
[
{
"name": "client",
"directory": "{root[work]}/{folder[name]}/{product[name]}",
"file": "{folder[name]}_{product[name]}_{@version}<_{output}><.{@frame}>.{ext}"
},
{
"name": "previews",
"directory": "{root[work]}",
"file": "{folder[name]}_{product[name]}_{@version}<_{output}><.{@frame}>.{ext}"
},
{
"name": "per_asset",
"directory": "{root[work]}/{folder[name]}",
"file": …
```
=> Bugfix: Fix delivery action in tray loader

client/ayon_core/hosts/houdini/plugins/create/create_arnold_rop.py, client/ayon_core/hosts/houdini/plugins/create/create_karma_rop.py, client/ayon_core/hosts/houdini/plugins/create/create_mantra_rop.py, client/ayon_core/hosts/houdini/plugins/create/create_redshift_rop.py, client/ayon_core/hosts/houdini/plugins/create/create_vray_rop.py
Transfer the render target setting from pre-create data to instance data, making sure the setting in the creator tab aligning to that in the publish tab
n/a
1. Create ROP instance
2. Choose your preferred render option(local, farm)
3. Go to Publish Tab and check the related setting
4. It should be aligned with what you set in the creator.
=> Houdini: Transfer Render Targets settings from pre create to instance when creating ROP instances

client/ayon_core/cli.py
Check for correct first argument.
It was checking for start.py when running from build and for python.exe when running from code which is oposite.
1. Command `run` should remove first argument correctly.
=> Chore: Run commnad fix

client/ayon_core/addons/applications/ayon_applications/__init__.py, client/ayon_core/hosts/traypublisher/plugins/create/create_editorial.py, client/ayon_core/hosts/unreal/api/__init__.py, client/ayon_core/modules/loader_action.py, client/ayon_core/scripts/slates/slate_base/base.py, client/ayon_core/tools/publisher/control_qt.py, client/ayon_core/tools/tray/tray.py, client/ayon_core/tools/utils/color_widgets/color_inputs.py, client/ayon_core/tools/utils/widgets.py
Small code cleanup. Mark unused variables and imports that have purpose to be ignored by linters, or removed the variables. Added imported variables to `__all__`. Converted lambda to function. Use better variable naming.
PR related to https://github.com/ynput/ayon-core/pull/196.
1. Logic did not change. Validate if it's true.
=> Chore: Small code cleanup

client/ayon_core/hosts/tvpaint/plugins/load/load_workfile.py
Workfile load plugin in TVPaint did use unavailable variable for file template.
1. Workfile loader works in TVPaint.
=> TVPaint: Fix filename formatting in workflie load plugin

client/ayon_core/lib/plugin_tools.py
Convert only string values in prepare data and keep others unchanged.
Before this PR the function would crash on any other type than string (e.g. on integer).
=> Chore: Prepare data does care only about string values

client/ayon_core/hosts/substancepainter/plugins/create/create_textures.py
This PR is to add missing 8k option into texture size setting in the texture creator
n/a
1. Launch Substance Painter
2. The `Size` Setting of Create TextureSet now supports the 8k texture exports.
=> Substance Painter: add missing 8k option into texture export size setting in the texture creator

client/ayon_core/hosts/maya/plugins/publish/validate_scene_set_workspace.py
Fix formatting of `root_dir` variable.
n/a
1. Open a file that is not in the current workspace of your context
2. The validation report should list the folder it should be in, instead of printing `{root_dir}` as text.
=> Maya: Validate Maya Workspace fix report not formatting the root dir variable

client/ayon_core/hosts/hiero/plugins/publish/precollect_instances.py
Fix variable used to calculate instance name.
There was used variable `subset` instead of `product_name` to calculate instance name. Also removed duplicated code receiving product name from tag data.
1. Precollect instances works.
=> Hiero: Precollect instances variable fix

client/ayon_core/hosts/maya/plugins/publish/extract_camera_mayaScene.py
Preserve (customized) image plane sizing on camera publishing
Fixes #411 
1. Apply an image plane to the camera
2. Change the Placement > "size" of the image plane
3. Publish the camera
4. The image plane's placement should be preserved
For completeness sake - also test some other attributes, like "Fit", "Offset", "Depth", "Rotate", etc. that an artist may customize on Image Planes - those values should also be preserved.
=> Maya: Publish camera preserve image plane size

client/ayon_core/pipeline/farm/pyblish_functions.py
Port of https://github.com/ynput/OpenPype/pull/6240
1. Configure Redshift render in Maya for multipart EXR and add Cryptomatte AOVs.
2. Publish and validate that only the main render instance has "multipartExr": true in the metadata json.
=> Maya: Fix Redshift cryptomatte multipartEXR

client/ayon_core/hosts/blender/addon.py, client/ayon_core/hosts/blender/hooks/pre_pyside_install.py
Fix installation of Qt binding.
Newer version of blender is using newer version of python which does not support PySide2, but does support PySide6. So PySide6 is used instead. Also new version of python does install the package to different place on windows which is fixed by using `--prefix` leading to blender python root.
1. Qt binding is automatically installed to blender 4
2. Blender integration works.
=> Blender: Qt binding fix for blender 4

client/ayon_core/hosts/fusion/hooks/pre_fusion_launch_menu_hook.py
Fusion: Launch menu hook fix PreLaunchHook import
Fix after refactor of separating ayon applications addon.
Fixes:
```
WARNING:ayon_core.lib.python_module_tools:Failed to load path: "E:\dev\ayon-core\client\ayon_core\hosts\fusion\hooks\pre_fusion_launch_menu_hook.py"
File "E:\dev\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
module = import_filepath(full_path, mod_name)
File "E:\dev\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
module_loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "E:\dev\ayon-core\client\ayon_core\hosts\fusion\hooks\pre_fusion_la …
```
=> Fusion: Launch menu hook fix PreLaunchHook import

client/ayon_core/addon/base.py
Validate correct version of applications addon.
There was a bug in applications addon version for validation of compatibility with ayon core.
1. Applications addon is loaded and applications can be launched.
=> Chore: Correct applications addon version

server_addon/deadline/server/settings/main.py
Fix Deadline Server addon.
Fixes:
```
Failed to initialize addon /addons/deadline/0.1.10
File "/backend/ayon_server/addons/definition.py", line 92, in versions
self.init_addon(version_dir)
File "/backend/ayon_server/addons/definition.py", line 156, in init_addon
module = import_module(vname, server_module_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/backend/ayon_server/addons/utils.py", line 18, in import_module
spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/addons/deadline/0.1.10/server/__init__.py", line 6, in <module>
from .settings import DeadlineSettings, DEFAULT_VALUES
File …
```
=> Fix usage of `BaseServerAddon` when only imported for type checking

client/ayon_core/pipeline/workfile/workfile_template_builder.py, client/ayon_core/tools/workfile_template_build/lib.py
Fix some typos/grammar and docstrings in Workfile Templates
n/a
1. Review the code changes.
2. Workfile templates should still work (but reviewing code might already suffice, it's mostly cosmetics)
=> Chore: Fix typos/grammar and docstrings in Workfile Templates

client/ayon_core/pipeline/workfile/workfile_template_builder.py
Do not use data from representation `"context"` values, instead use values from parent entities.
Modification should fix loading of representations without `"asset"` and `"subset"` in their `"context"` values that should be used for template fill. Issue discovered with https://github.com/ynput/ayon-core/pull/330 .
1. Workfile template builder should be able to load representations without the values
=> Chore: Workfile template builder context usage fix

client/ayon_core/tools/workfiles/widgets/files_widget_workarea.py, client/ayon_core/tools/workfiles/widgets/window.py
By default select the file with the latest date modified..
Fixes #434 
Note: in some odd cases where an artists saves over an older version than that file will have the latest date modified and hence will be selected. It's not the latest version, but latest date modified.
1. Open workfiles tool
2. Browsing different tasks and folders should always default to selecting the latest workfile.
3. It should feel logical for the majority of production cases.
4. Clicking refresh in the UI should not change the selection.
=> Workfiles: Select latest workfile automatically

client/ayon_core/tools/workfiles/widgets/window.py
Alway refresh workfiles tool on show so that when closing and reopening it does not show old outdated data.
Note: this also refreshes when the window is minimized and then brought up again
Fixes #397
1. Open workfiles tool, close it.
2. Publish your scene (or do something else that increments you workfile without using the workfiles tool itself)
3. Reopen workfiles tool.
4. It should now also list the newly created file.
=> Workfiles: Always refresh workfiles tool on show

server_addon/create_ayon_addons.py
Fix import of `importlib.machinery` in create package script.
1. Create ayon addons script works.
=> Chore: Fix import in create ayon addons

server_addon/applications/package.py
Applications addon has defined compatibility.
Changes are related to https://github.com/ynput/ayon-backend/pull/127 as it is new feature, not released on server, and because core 0.3.1 is not yet out, the version of addon is kept at 0.2.0.
1. This change can be tested only with https://github.com/ynput/ayon-backend/pull/127
2. It would not be allowed to create bundle with applications 0.2.0 addon and core 0.3.0 or lower.
=> Applications: Define compatibility of addon

client/ayon_core/hosts/houdini/hooks/set_default_display_and_view.py, client/ayon_core/hosts/houdini/plugins/create/create_review.py, client/ayon_core/hosts/houdini/plugins/publish/validate_review_colorspace.py
This error happens when admins update core addon without updating Houdini addon.
which can result in an error in this Houdini hook `SetDefaultDisplayView` and some review publish plugins because an expected Houdini setting won't be available which will raise an error. 
An alternative solution to split the Addons which by design won't update the client code of Houdini without uploading the new addon.
I don't know whether this PR should be merged or we should just wait till the addons be split. 
Maybe @iLLiCiTiT can tell
Launching Houdini with the latest develop while not uploading the new Houdini addon shouldn't raise errors. 
you can do so by using Ayon in dev mode and pull latest `develop`.
=> Houdini fails to start because missing settings

client/ayon_core/hosts/maya/tools/mayalookassigner/vray_proxies.py
Fixes Maya Look Assigner import in `vray_proxies` logic.
Fixes:
```python
```
Not entirely sure when the error occurs - maybe directly when opening the look assigner? Just got it reported to me by an artists.
1. Maya Look Assigner should work.
=> Maya: Fix VRay Proxies look assigner import

client/ayon_core/lib/__init__.py, client/ayon_core/lib/cache.py, client/ayon_core/pipeline/anatomy/anatomy.py, client/ayon_core/tools/common_models/cache.py, client/ayon_core/tools/common_models/hierarchy.py, client/ayon_core/tools/common_models/projects.py, client/ayon_core/tools/common_models/thumbnails.py, client/ayon_core/tools/loader/models/actions.py, client/ayon_core/tools/loader/models/products.py, client/ayon_core/tools/loader/models/sitesync.py
We have implemented multiple different approaches how to cache data, usually the same. Goal of this PR is to have one in `ayon_core.lib` that can be used across the board. Using the items in `Anatomy` as first step.
The classes were taken from `ayon_core.tools.common_models.cache` where were used for model data. There are 2 classes, one for storing the data, second for nesting them in specific level. The nesting was usually done using lambda functions.
1. Anatomy caching still works.
2. Validate implementation of the classes.
=> Chore: Move cache item to lib

client/ayon_core/hosts/maya/plugins/publish/extract_assembly.py, client/ayon_core/hosts/maya/plugins/publish/extract_proxy_abc.py, client/ayon_core/hosts/maya/plugins/publish/extract_unreal_skeletalmesh_abc.py
Fixes refactoring of https://github.com/ynput/ayon-core/pull/336 from `lib` to `alembic` module.
Fixes errors like:
```
Filepath:
E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\publish\extract_unreal_skeletalmesh_abc.py
Traceback:
File "E:\dev\ayon-core\client\ayon_core\pipeline\publish\lib.py", line 257, in publish_plugins_discover
module = import_filepath(abspath, mod_name)
File "E:\dev\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
module_loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "E:\dev\ayon-core\client\ayon_core\hosts\maya\plugins\publish\extract_unreal_skeletalmesh_abc.py", line 8, in 
from ayon_core.hosts.maya.api.lib import ( …
```
=> Maya: Fix `extract_alembic` imports

server_addon/deadline/package.py, server_addon/deadline/server/settings/publish_plugins.py
`validate_unique_names` cannot be used on fields that are just regular `list[str]`, they must be `list[SomethingSomething]`.
1. add some env variables in `ayon+settings://deadline/publish/NukeSubmitDeadline/env_allowed_keys`
2. no validation error should be thrown and values should be persisted
=> Fix validate_unique_names call

client/ayon_core/hosts/fusion/api/lib.py
Fix comp repair folder settings
Fixes:
```python
File "E:\dev\ayon-core\client\ayon_core\hosts\fusion\api\lib.py", line 172, in _on_repair
value = folder_attributes[key]
TypeError: 'float' object is not subscriptable
```
1. Save fusion comp with different settings than current folder
2. The "repair" button on the popup should work.
=> Fusion: Fix comp repair folder settings

server_addon/applications/client/ayon_applications/utils.py, server_addon/applications/package.py
The PR is to add support of the tools group environment per task level, as the current tools group environment only support for per folder level. If there is empty list of tools group setting up per task level, it will use the tools group per folder level instead if the tools group for the folder level is not empty.
It doesn't work well with Redshift in 3dsmax when both folder and task level has added Redshift as tools group. It will crash 3dsmax during launching it.
1. Go to` AYON server -> Studio Settings -> Application addon` to set up your environment for external plugins (e.g. Arnold, Redshift, Yeti)
2. Go to Project -> Select your project
3. Editor -> folder -> task
4. Set up your tools group for your task
=> Chore: Support adding tools group environment per task level

client/ayon_core/hosts/blender/api/plugin.py
Extraction of the review in Blender was failing in case of objects not in `OBJECT` mode because the `deselect_all` function didn't implement the context override.
1. Set any object in the scene as `EDIT` mode.
2. Try publish a review. It should publish normally.
=> Blender: Fix deselect all function with context override

client/ayon_core/tools/publisher/widgets/card_view_widgets.py, client/ayon_core/tools/publisher/widgets/list_view_widgets.py, client/ayon_core/tools/publisher/widgets/overview_widget.py, client/ayon_core/tools/publisher/window.py
Double click on instances under `Create` tab changes tab to `Publish`.
The double click is ignored if happens on checkbox or button. Double click on instances group does not change the tab either.
**Additional context**
Source issue description https://github.com/ynput/OpenPype/issues/4567
=> Publisher: Double click at instance switch to publish tab

client/ayon_core/lib/__init__.py, client/ayon_core/lib/ayon_info.py
Implemented helper function `is_in_ayon_launcher_process` to determine if current process is AYON launcher.
Some functionality should be available only in AYON launcher process but there is not "unified" function that would help to determine that. This function is simplified and can be enhanced in future if we find out there may be other issues.
1. Function `is_in_ayon_launcher_process` returns `True` in AYON launcher process
2. Function `is_in_ayon_launcher_process` returns `False` in any other process (e.g. in maya)
```python
from ayon_core.lib import is_in_ayon_launcher_process
print(is_in_ayon_launcher_process())
```
=> Chore: Be able to determine if is in AYON launcher process

client/ayon_core/hosts/blender/plugins/load/load_camera_abc.py
Use transform cache constraints to update alembic cameras.
Before, the camera was deleted and recreated. Now it updates the cache file.
This PR should be compatible with existing alembic cameras loaded in the scene. When updating, it will create a new transform cache, if it doesn't find one.
To assign the right object path, it has been necessary a workaround to force Blender to evaluate the cache file loaded. This is because the list of object paths in the cache file is not available immediately when the file has been loaded (https://devtalk.blender.org/t/alembic-cachefile-list-of-object-paths-not-available-at-creation/21573).
1. Try loading alembic cameras. They should have a Transform Cache in the object constraints.
2. Make changes to the camera (for instance, change field of view). …
=> Blender: Use transform cache to handle alembic camera updates

client/ayon_core/pipeline/context_tools.py
Removed function that used concept of "session" which is not available anymore in ayon core.
1. Validate the function is not used.
=> Removed deprecated function 'get_template_data_from_session'

client/ayon_core/pipeline/colorspace.py, client/ayon_core/scripts/ocio_wrapper.py
Move all colorspace logic to `colorspace.py` which is only imported in ocio wrapper.
Wrapper is now just simple cli that calls functions from colorspace and stores result into output json. Code from wrapper was moved to `colorspace.py`. Moved functions areound, deprecated functions are at the bottom.
Validation of compatible `PyOpenColorIO` now also checks version of the module.
1. Colorspace logic should work almost anywhere.
=> Colorspace: Enhancement of subprocess getters

client/ayon_core/pipeline/colorspace.py
Use kwargs to pass project entity to Anatomy initialization.
Project entity was passed in as site name instead of project entity.
- Make sure you have core with new imageio color settings (or create package from this PR and upload to server to be sure).
1. Enable colormanagement in core addon.
2. Launch host of your choice (should have ability to run python scripts)
3. Run this
```python
from ayon_core.pipeline.colorspace import get_current_context_imageio_config_preset
get_current_context_imageio_config_preset()
```
It should not crash.
=> Colorspace: Fix Anatomy object initialization

client/ayon_core/tools/push_to_project/models/integrate.py
Lower task name when is used, and not when it can be `None`.
Quick fix without knowing full context -> missing test notes @MustafaJafar fill if you can.
=> Push to Project: Fix task lowering

client/ayon_core/plugins/publish/validate_containers.py, server/settings/publish_plugins.py, server_addon/aftereffects/package.py, server_addon/aftereffects/server/settings/publish_plugins.py, server_addon/harmony/package.py, server_addon/harmony/server/settings/main.py, server_addon/harmony/server/settings/publish_plugins.py, server_addon/houdini/package.py, server_addon/houdini/server/settings/publish.py, server_addon/maya/package.py, server_addon/maya/server/settings/publishers.py, server_addon/nuke/package.py, server_addon/nuke/server/settings/publish_plugins.py, server_addon/photoshop/package.py, server_addon/photoshop/server/settings/publish_plugins.py
Added profile based settings for Validate Content publish plugin.
The settings will change behavior of the plugin based on host name. The plugin is disabled if host does not support load functionality, or there are no profiles. Removed settings of the plugin from other hosts.
We should do this for the move of hosts. The first encounter happened in https://github.com/ynput/ayon-core/pull/516 .
1. Create package of core and all changed host addons (AE, PS, Nuke, Maya, Houdini, Harmony).
2. Launch DCC of one of the host integrations.
3. Validate Content should be there and can be disabled (with default settings).
4. Based on changed settings the plugin should change it's state -> remove all profiles, remove the host from list, add new hosts, change optional state etc.
=> Chore: Validate Content plugin settings

client/ayon_core/plugins/publish/validate_containers.py, server/settings/publish_plugins.py
Rename `ValidateContainers` to `ValidateOutdatedContainers`.
=> Chore: Validate Content plugin settings 2

client/ayon_core/tools/launcher/ui/actions_widget.py
Call update on viewport instead on view.
Method `update` on view does update single index which should be passed in, but it is not. The bug was discovered with PySide6.
```
File ".\client\ayon_core\tools\launcher\ui\actions_widget.py", line 362, in _on_model_refresh
self._view.update()
TypeError: QListView.update() takes exactly one argument (0 given)
```
You would have to use macOs or force using PySide6 in AYON launcher (for other platforms).
1. Start ayon launcher with console.
2. In tray open `Launcher` tool.
3. Select project and change context few times.
4. The traceback should not be raised.
- With PySide2 launcher tool works as expected too.
=> Launcher tool: Fix view update

server_addon/create_ayon_addons.py
Change how `version.py` text looks like and use addon name in it.
There is not yet such addon which uses this functionality, but right now would be filled with "AYON core" which is not right.
=> Chore: Add addon name to 'version.py' of server packages

client/ayon_core/hosts/houdini/plugins/publish/collect_local_render_instances.py, client/ayon_core/hosts/houdini/plugins/publish/extract_render.py
Disable integration for original render instance when publishing locally
1. Launch Houdini
2. Publish Render locally and on farm.
=> Houdini: Disable integration for the original render instance when publishing locally

client/ayon_core/tools/launcher/models/actions.py, client/ayon_core/tools/launcher/ui/actions_widget.py
Sort action items by identifier so their order doesn't keep changing on every launch.
1. Open Launcher
2. Actions should be sorted
=> Launcher: Make sure actions in Launcher are sorted

server/settings/publish_plugins.py
Fix typo `Produt types` to `Product types`.
=> Extract Burnin: Fix typo in settings label

server_addon/photoshop/client/ayon_photoshop/plugins/publish/collect_color_coded_instances.py, server_addon/photoshop/client/ayon_photoshop/plugins/publish/collect_review.py, server_addon/photoshop/client/ayon_photoshop/plugins/publish/collect_version.py, server_addon/photoshop/client/ayon_photoshop/plugins/publish/extract_image.py, server_addon/photoshop/client/ayon_photoshop/plugins/publish/extract_review.py, server_addon/photoshop/client/ayon_photoshop/plugins/publish/validate_naming.py, server_addon/photoshop/client/ayon_photoshop/version.py, server_addon/photoshop/package.py
Add missing `settings_category` attribute to publish plugins.
1. Plugin settings are applied correctly.
=> Photoshop: Add missing settings category

server_addon/create_ayon_addons.py, server_addon/houdini/client/ayon_houdini/version.py
Create package script does not copy files around unless it was asked for. So if zip should be created, only file which is created on disk is output package zip.
Do most of the logic only in memory without copying files around. This means that `--keep-sources` argument does not have usage as there are no sources. But `--skip-zip` still can be used.
Changed docstring in houdini `version.py` (the template changed while PR was opened).
1. Running `python ./create_ayon_addon.py` should output the same packages as before but a little bit faster.
=> Chore: Create server addon package enhancements

client/ayon_core/tools/loader/control.py
Wrapped `get_containers` into try except block to avoid broken UI because of broken function implementation.
Added because of bugfix in [PR](https://github.com/ynput/ayon-core/pull/595). This is 3rd ocassion when loader UI was not showing anything to load because of bug in `get_containers`. Scene inventory would not work, but loader can be at least used to load.
=> Loader tool: Safe containers discovery

server_addon/applications/package.py, server_addon/maya/package.py
Define `client_dir` in the addons so their client code is created.
1. Created packages of the addons contain `client.zip` in private.
=> Chore: Fix creation of applications and maya packages

client/ayon_core/cli_commands.py
Report exception info when CLI command failed to be added from an addon.
Before:
```
*** WRN: >>> { CLI-AddModules }: [  FAILED to add cli command for module "launch_scripts"  ]
```
After:
```
*** WRN: >>> { CLI-AddModules }: [  FAILED to add cli command for module "launch_scripts"  ]
==============================
'Group' object has no attribute 'name'
==============================
File "E:\dev\ayon-core\client\ayon_core\cli_commands.py", line 33, in add_addons
addon.cli(click_func)
File "E:\dev/ayon-launch-scripts/client\ayon_launch_scripts\addon.py", line 24, in cli
click_group.add_command(cli_main)
File "C:\Users\User\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403061937_windows.zip\dependencies\click\core.py", line 1839, in add_command
name …
```
=> Report exception info when CLI command failed to be added.

client/ayon_core/lib/attribute_definitions.py
Attribute Definitions HiddenDef: fix `super` call
n/a
1. Attribute Definitions should still work
=> Attribute Definitions HiddenDef: fix `super` call

client/ayon_core/tools/launcher/ui/hierarchy_page.py
Fix minor typo in code.
n/a
1. Hierarchy page in launcher should still work
2. Refresh button in launcher should still work on hierarchy page
=> Fix typo `_on_refreh_clicked` -> `_on_refresh_clicked`

client/ayon_core/plugins/publish/extract_color_transcode.py
Actually format the representation name into the log message
n/a
1. Representation name should be logged when no colorspace data
=> Extract Color Transcode: Fix log message formatting

client/ayon_core/plugins/publish/extract_color_transcode.py
Plugin `Transcode color spaces` does remove only representations that were processed by the plugin.
1. Not having profiles for specific context in `Transcode color spaces` should not cause that all reviews are skipped
=> Chore: Transcode color spaces plugin does not remove all representations

client/ayon_core/plugins/publish/extract_color_transcode.py
Fix duplicated function `_rename_in_representation`
Avoids redeclaration
1. Extract Color Transcode should still work
=> Extract Color Transcode: Fix duplicated function `_rename_in_representation`

server_addon/max/client/ayon_max/api/pipeline.py
This PR is to make sure the loaded asset showed up scene inventory.
n/a
1. Launch Max
2. Load any asset
3. Go to AYON -> Manage
4. Loaded assets should show up correctly
=> Max: fix scene inventory not shown up

client/ayon_core/tools/sceneinventory/models/containers.py, client/ayon_core/version.py
`name` isn't used anywhere but it is hard required, causing crashes in hosts that are not having it. Also adding broad try/except to catch any invalid containers so they won't crash the whole list.
Scene inventory should list loaded stuff even without `name` - currently this affects Unreal as far as I know.
=> Scene Inventory: remove unused container attribute

client/ayon_core/tools/loader/abstract.py
Change order of hero version in versions combobox so hero version is under standard version.
When hero version is higher then hero version is first option to use for load which is unconventional.
1. Loader tool should preselect last standard version even if there is hero version with same value.
=> Loader tool: Hero version is smaller than standard version

client/ayon_core/scripts/otio_burnin.py
Try to auto-fix usage of `shell=True` in burnin script.
In some cases the shell set to `True` might cause that the subprocess don't have access to the executable. Ideal case would be to not use `shell=True` at all, that would require more modifications. To avoid it we can run "testing" ffmpeg command and change it to `False` if it crashes.
=> Chore: Burnin script shell execution

client/ayon_core/hosts/houdini/plugins/publish/collect_local_render_instances.py
This PR extends #447 and make it work with local Houdini render
1. Update these settings on ayon server: _you can take reference from my screenshots below._
- `ayon+settings://core/tools/creator/product_name_profiles`
- `ayon+anatomy://{my-project}/templates/publish/1` _render template._
2. Launch Houdini 
3. Publish Render locally. Here's what to expect:
- you should find the names of the created runtime instances follow your the template profile
- you should find the location of the published render follow your render template (we add support for two more keys `renderlayer` and `aov`)
Here are some snippets of my settings. 
**Render template:** 
**product_name_profiles:**
=> Use product name templates for render products on local Houdini render

client/ayon_core/tools/workfiles/abstract.py, client/ayon_core/tools/workfiles/control.py, client/ayon_core/tools/workfiles/models/workfiles.py, client/ayon_core/tools/workfiles/widgets/files_widget_workarea.py, client/ayon_core/tools/workfiles/widgets/side_panel.py
Selection of context in workfiles tools does correctly resolve workfile entity from AYON and new workfile can save note.
When context is changed from a folder 1 to folder 1 and they have the same tasks then there is a chance that workfile entity is not loaded for correct task. And when new workfile is created, it was not possible to change note because we didn't have access to workfile entity id.
1. Create new workfile using workfiles tools.
2. Set note on the workfile and hit save.
3. It should save the note.
1. Make sure you have 2 folders with same tasks.
2. Open last workfile on one of the tasks on folder 1.
3. Open workfiles tool.
4. Set some note on the workfile (this is how we find out it works).
5. Change folder to folder 2 (The task should stay selected).
6. Change folder to …
=> Workfiles tool: Context selection is properly propagated to workarea

client/ayon_core/tools/common_models/users.py, client/ayon_core/tools/workfiles/control.py
Fixed implementation of users model in workfiles tool.
Only admin and manager users can see all users, other users can see only other users assigned to same projects. It is necessary to add project name filtering to users GraphQl, which requires fix in ayon-python-api, for now the code from ayon api was copied next to users model.
1. Create artist user and assign him to a project.
2. Start AYON launcher as the user.
3. Use host integration of your choice and open workfiles tool.
4. It should not crash, and should show user full name.
=> Workfiles tool: Artists can see users

server_addon/houdini/client/ayon_houdini/plugins/create/create_hda.py, server_addon/houdini/client/ayon_houdini/plugins/load/load_hda.py
Fix a bug when publishing different HDA products from different folder paths with the same product name.
About the bug: product name was being used for HDA `type name` and `type label`. 
when publishing HDA from different folder paths with the product name results in having multiple HDAs/Houdini nodes with the 
`type name`. which makes houdini thinks they are the same HDA. 
1. Publish HDAs from different folder paths, _maybe different projects too_.
2. Load the published HDAs.
=> Houdini: Publish different HDA products from different folder paths with the same product name

client/ayon_core/tools/sceneinventory/select_version_dialog.py, client/ayon_core/tools/sceneinventory/view.py
Scene inventory can change version for whole selection, but does not show statuses next to version if are from different products.
Sometimes it might be helpfull to change version for multiple loaded products at the same time. But we're not able to show status in that case, lazy solution is to hide the statuses to avoid confusion.
1. It is possible to change version of multiple containers from different products in scene manager tool.
=> Scene Inventory tool: Set version dialog can change version for whole selection

client/ayon_core/tools/workfiles/widgets/files_widget_published.py
Fix work with published workfiles in workfiles tool.
There was a bug in Qt model when receiving data for specific roles.
1. Published workfiles can be opened/copy-pasted.
=> Workfiles tool: Published files can be copied/opened

client/ayon_core/tools/loader/control.py
Use import from new location of `NestedCacheItem` and `CacheItem`.
1. Loader tool still works.
=> Loader: Fix deprecated import

client/ayon_core/vendor/python/scriptsmenu/launchformaya.py
This PR is to fix the bug found during the launch of Maya 2025.
```
Error: TypeError: file C:\Users\murph\AppData\Local\Ynput\AYON\addons\core_0.4.0\ayon_core\vendor\python\scriptsmenu\launchformaya.py line 133: int() argument must be a string, a bytes-like object or a real number, not 'KeyboardModifier'
```
n/a
1. Launch Maya with different versions
2. Check Script Editor
3. the scriptmenu related error should be gone
=> Maya: Fix the scriptmenu error found during launch maya 2025

server_addon/houdini/client/ayon_houdini/api/lib.py, server_addon/houdini/client/ayon_houdini/api/pipeline.py
Support opening workfile on launching Houdini.
Also, it removes  the redundant if statement. 
For future reference 
This doesn't work 
```python
if os.environ.get("AYON_WORKFILE_TOOL_ON_START"):
hdefereval.executeDeferred(host_tools.show_workfiles(parent=hou.qt.mainWindow()))
```
but, this works!  :'D 
```python
if os.environ.get("AYON_WORKFILE_TOOL_ON_START"):
hdefereval.executeDeferred(lambda: host_tools.show_workfiles(parent=hou.qt.mainWindow()))
```
1. Enable `ayon+settings://core/tools/Workfiles/open_workfile_tool_on_startup`
2. Launch Houdini
=> Houdini: support opening workfile on launch

client/ayon_core/tools/common_models/__init__.py, client/ayon_core/tools/common_models/projects.py, client/ayon_core/tools/sceneinventory/model.py, client/ayon_core/tools/sceneinventory/models/containers.py, client/ayon_core/tools/sceneinventory/view.py
Scene inventory tool now can update to latest approved version.
This is a proposal how it could be implemented, we still need to modify validator which checks versions of loaded containers. The latest approved version is determined by Status "state" which has 4 options `"not_started"`, `"in_progress"`, `"done"` and `"blocked`. We use `"done"`.
~~Function `get_outdated_containers` now does not mark last approved as outdated > not sure if this is an issue or enhancement?~~ Reverted
1. Scene inventory should be able to load latest approved version.
=> Scene Inventory: Action to update to latest approved version

server_addon/maya/client/ayon_maya/plugins/publish/collect_fbx_model.py, server_addon/maya/client/ayon_maya/version.py, server_addon/maya/package.py, server_addon/maya/server/settings/publishers.py
This PR is to add support to publish fbx in model product type in Maya
Update maya addon to 0.2.8
1. Go to your AYON server, make sure `Collect Model for FBX export` enabled
2. Launch Maya
3. Create Model Instance
4. You can choose to turn on/off `Collect Model for FBX Export`
5. If you turn on, it will publish fbx with model product type.
=> Maya: Publishing fbx in model family

server_addon/deadline/server/settings/publish_plugins.py, server_addon/houdini/server/settings/publish.py
Remove dot `.` from title at end of plug-in names in settings
Removes the dots at the end of plug-in labels seen at the bottom here.
+ some PEP8 cosmetics
1. Check the changes - nothing should change in code behavior.
=> Settings: Minor cosmetic tweaks

server_addon/houdini/client/ayon_houdini/plugins/publish/extract_active_view_thumbnail.py, server_addon/houdini/server/settings/publish.py
Exposes the Extractor that takes a quick screenshot of the active view to settings to allow disabling/enabling it.
Unfortunately we've been having some crashes with Houdini on this logic on a very heavy scene with heavy VDBs - unsure why and it's been inconsistent unfortunately, making it hard to debug and detect whether there's a way to report a bug to sidefx and have them fix Houdini.
This change now allows us to disable it for that project.
1. Tweak the settings
2. The Extract Active View Thumbnail should behave accordingly
=> Houdini: Expose Extract Active View Thumbnail to settings

client/ayon_core/tools/publisher/models/publish.py
Remove used `Literal` typehint.
Typehint `Literal` is breaking older DCCs with Python older than 3.8.
1. Publisher works in those DCCs.
=> Publisher: Remove Literal typehint

client/ayon_core/lib/transcoding.py
Removed deprecated `-intra` command from ffmpeg burnins commands.
1. Burnins are created and playable.
=> Burnins: Remove deprecated ffmpeg argument

client/ayon_core/tools/utils/lib.py
Cache key expect values to be `None` and `QColor`.
Issue discovered in https://github.com/ynput/ayon-core/pull/764#pullrequestreview-2169128475 causing that `Set version` on multiselection does not work as it request icon and color set as `None` . That already happened few times, always causing crashes of UI, so maybe we should expect broken values and show empty icons rather than crashing tools.
1. Set version in scene inventory does work on multiselection of multiple different products.
=> UI Icons: Cache key is safely generated

client/ayon_core/tools/loader/ui/statuses_combo.py
Change placeholder text from "Statuses..." to "Version status filter..." to align more with the filter fields to left of it.
Before:
After:
For context - there's also a "Folder name filter..." a bit further left.
1. Loader should display the new "Version status filter..." placeholder text
=> Loader: Change placeholder text to "Version status filter..."

client/ayon_core/addon/base.py, client/ayon_core/addon/interfaces.py, client/ayon_core/host/dirmap.py, client/ayon_core/host/host.py, client/ayon_core/host/interfaces.py, client/ayon_core/lib/attribute_definitions.py, client/ayon_core/lib/file_transaction.py, client/ayon_core/lib/local_settings.py, client/ayon_core/lib/path_templates.py, client/ayon_core/pipeline/create/creator_plugins.py, client/ayon_core/pipeline/project_folders.py, client/ayon_core/pipeline/publish/abstract_collect_render.py, client/ayon_core/pipeline/publish/abstract_expected_files.py, client/ayon_core/pipeline/schema/__init__.py, client/ayon_core/pipeline/workfile/workfile_template_builder.py, client/ayon_core/plugins/publish/extract_burnin.py, client/ayon_core/plugins/publish/extract_review.py, client/ayon_core/plugins/publish/integrate.py, client/ayon_core/style/__init__.py, client/ayon_core/tools/common_models/hierarchy.py, client/ayon_core/tools/launcher/abstract.py, client/ayon_core/tools/loader/abstract.py, client/ayon_core/tools/publisher/publish_report_viewer/window.py, client/ayon_core/tools/workfiles/abstract.py
As we moved from Python 2 we don't need to use `six` module anymore.
Code where `six` module was used for Py2 and Py3 compatibility is not used anymore. There are still places where `six` is used but those are not as simple changes as these.
Replaced `six.string_types` with `str`. Instead of using `six.add_metaclass` is used `ABC` base class to define metaclass, or creation of class defines `metaclass=...` in creation. Replaced `six.reraise` with simple raise of exception, and some special cases are using different traceback.
1. Go through code and validate the changes.
=> Chore: Reduce 'six' usage

client/ayon_core/plugins/load/delete_old_versions.py
Add informative confirm prompt for delete versions to avoid accidental clicks deleting versions and files.
With "Show details..." clicked:
1. Open Loader from Tray
2. Use Delete Old Versions action
3. Deletion should be confirmed (and do nothing when cancelled!)
=> Delete old versions: Add confirm prompt to avoid accidental delete

client/ayon_core/pipeline/create/context.py, client/ayon_core/pipeline/workfile/workfile_template_builder.py
Workfile Template Builder: Allow Create Placeholder to define the 'active' state of the created instance.
Example in Houdini using https://github.com/ynput/ayon-houdini/pull/36
The template:
After template build:
> would be nice to test in Nuke and Maya if it does not break anything.
>    Use old template where are placeholders without active.
>    Use new template and try if it creates activated/deactivated instances based on the placeholder data.
1. Test whether this works when creating create placeholders in other hosts, like:
and bugfix https://github.com/ynput/ayon-houdini/pull/41 )
2. Existing create placeholders in an existing template should still work and default to active.
=> Workfile Template Builder: Allow Create Placeholder to define the 'active' state

client/ayon_core/tools/loader/ui/products_delegates.py, client/ayon_core/tools/loader/ui/products_model.py, client/ayon_core/tools/loader/ui/products_widget.py
Loader tool can enable/disable grouping of products and filtering by product types and status names should work.
~~This was broken with new statuses filter which required to pass status names on model refresh, which was mid-solution that is not necessary at the end. So changed the logic of Products model refresh back to previous integration to not require status names on refresh.~~
PR changed during it's lifetime as was discovered that the whole filtering was not working. Product type filtering was completelly broken and statuses filtering did break UI for multiselection of folders. Also products under group item did not propagate version change from combobox in specific cases.
- First of all grouping can be enabled/disabled.
- To validate we didn't break the source of the previous …
=> Loader tool: Fix filtering

client/ayon_core/cli.py, client/ayon_core/cli_commands.py
Create AddonsManager only once for cli processing.
Create only AddonsManager object only single time for whole main cli processing which should make the startup a little bit faster as it does not need to re-fetch all the data.
1. All command line commands are working as expected.
2. The most affected commands are `extractenvironments` and `publish` which now do not create addons manager bu expect it as argument. Both are used on farm.
=> Chore: Faster cli initalization

client/ayon_core/cli.py, client/ayon_core/cli_commands.py, client/ayon_core/tools/tray/lib.py
Added option to force start of tray.
Using `--force` will kill existing tray process and start a new one. Can be used when tray is for some reason stuct and artist should be able to continue.
1. Create package and upload to server, or use dev path (server part is not needed).
2. Start a tray in one terminal.
3. Start a tray in second terminal > this should tell you that tray is already running.
4. Start a tray in second terminal with `--force` argument > previous tray should stop and new should start.
=> Tray: Force start tray

client/ayon_core/tools/tray/lib.py
Check if the PID defined in tray info file is alive to make validation of starting tray faster.
It happened to me that if tray is brute-force shutdown it does not cleanup the file, so next tray startup takes 10 seconds. Added check if the PID is still alive before any other check.
Not sure how to exactly replicate the issue. I've started tray in terminal and killed the terminal tab when splash showed up. With that done, the next startup takes at about 10 seconds. With this PR it should be faster.
=> Tray: Make starting tray check faster

client/ayon_core/addon/base.py
Tweak grammar plus make it more understandable what addon needs updating
Related to discussion where this appeared in the logs on a failed deadline render - but the actual issue was a connection timeout.
1. Use this ayon-core version but an older version of `ayon-maya` (e.g `0.1.x`) in your bundle.
2. Launching tray should likely show this error in console.
=> Tweak grammar for "Addon is not available" due to outdated version for moved addon from core

client/ayon_core/tools/tray/lib.py
If tray should be started with different user the other runnig tray is shutdown.
This is required for webactions. It is not gracefull, it does not show any warning message, but it is at the same time an edge case so it is not high priority to handle it gracefully.
1. Make sure to have 2 different users in AYON.
2. Create package, upload to server and use in bundle.
3. Start AYON launcher.
4. Login as userA and start tray (keep it running).
5. Open new terminal and start ayon with `ayon_console.exe --ayon-login`.
6. Login as userB.
7. Tray should start and tray from step 4. should shut down.
=> Tray: Start tray with different user

client/ayon_core/tools/tray/lib.py
Logout does not keep tray running.
The issue was that `get_default_settings_variant` from `ayon_api` is actually using global connection, which can't log in if we just logged out.
1. Create package, upload to AYON server and use in bundle.
2. Start AYON tray with console (so you can see if it is closed).
3. Click on tray icon > Login.
4. In opened dialog click on Logour and confirm with Ok.
5. You should be logged out and tray should fully close.
=> Tray: Logout closes tray

client/ayon_core/tools/sceneinventory/model.py
All containers that are not from last version have marked version with red color.
Adding last approved versions logic to scene inventory stopped to mark last approved versions with red color, which is causing confusions.
1. Create version 1 of a product and change status to approved.
2. Create version 2 on the same product and use other than approved status.
3. Load version 1 into a scene.
4. Open scene inventory tool.
5. The container in view should have red colored version label.
Related to issue https://github.com/ynput/ayon-core/issues/789 , does notresolve the issue fully.
=> Scene Inventory tool: All outdated containers use red color of version

server/settings/publish_plugins.py
Original `acc` doesnt work for audio
Solves error `Unknown encoder 'acc'` in ExtractReview
1. publish something which will have review with attached audio file (from Hiero, maybe AE)
2. ExtractReview shouldnt fail
=> Use proper aac argument for ExtractReview

client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
Paragraphs contain detailed information on the changes made to the product or service, providing an in-depth description of the updates and enhancements. They can be used to explain the reasoning behind the changes, or to highlight the importance of the new features. Paragraphs can often include links to further information or support documentation.
Before: 
After:
Yay, pretty. 🎉 
1. Publish e.g. editorial or something that doesn't have the task paths (yet?) (in my case Resolve PR for new publisher)
=> Log message: Avoid double quotes around paths

client/ayon_core/pipeline/workfile/workfile_template_builder.py
Allow placeholder representation name to be set as an empty value to load all representations
Use case described by @fabiaserra [here](https://github.com/ynput/ayon-core/pull/871#issuecomment-2332185180).
1. Create load placeholder with empty representation name
2. It should load all representations
=> Workfile template build: Allow empty representation name

client/ayon_core/vendor/python/scriptsmenu/launchformaya.py
Maya 2025 scripts menu does not show any menu entries.
Reported [here](https://discord.com/channels/517362899170230292/1281462971897221121).
Previous fix https://github.com/ynput/ayon-core/pull/669 may have been wrong?
1. Launch Maya 2025
2. Scripts menu should log no errors on startup or menu open. 
3. The menu entries should be visible and work as intended.
=> Maya 2025: Should display scriptsmenu correctly instead of only search bar

client/ayon_core/pipeline/workfile/workfile_template_builder.py
Allow custom `resolve_template_path` to be implemented by AYON addon integrations
Related to Houdini workfile templates that allows extra path resolving using `hou.text.expandString`
1. Test together with https://github.com/ynput/ayon-houdini/pull/74
=> Workfile template builder: Allow custom `resolve_template_path`

client/ayon_core/plugins/publish/extract_review.py
Allow `.tif` and `.tiff` extensions as supported extensions for extract review.
Avoids the case where `tif` outputs are skipped for review generation due to their extension with log message:
> INFO: Representation has unsupported extension "tif"
Is there a reason this [doesn't use the transcoding list of extensions](https://github.com/ynput/ayon-core/blob/432ead8178e7f75229c67924e411f2ac6d3055e3/client/ayon_core/lib/transcoding.py#L47-L67)?
```python
from ayon_core.lib.transcoding import (
IMAGE_EXTENSIONS,
VIDEO_EXTENSIONS,
)
```
1. Publish a `.tiff` or `.tif` sequence with `review` enabled - it should generate the reviewable.
=> Allow `.tif` and `.tiff` extensions for review

client/ayon_core/scripts/slates/slate_base/items.py
Fix variable redeclaration.
Ported from https://github.com/ynput/OpenPype/pull/6314
1. Check code
=> Avoid redefinition of variable name in burnin OTIO

client/ayon_core/pipeline/create/context.py, client/ayon_core/pipeline/create/structures.py, client/ayon_core/tools/publisher/abstract.py, client/ayon_core/tools/publisher/control.py, client/ayon_core/tools/publisher/models/create.py, client/ayon_core/tools/publisher/widgets/card_view_widgets.py, client/ayon_core/tools/publisher/widgets/list_view_widgets.py, client/ayon_core/tools/publisher/widgets/widgets.py, client/ayon_core/tools/publisher/window.py
Create logic does allow to fill folder path and task name that are not validated in Publisher UI.
This change required change of context validation on instances. From now `CreatedIntance` does not have information about having valid context or not, it must be validated against `CreateContext`.
Added option to add `"has_promised_context"` to instance data. When set to `True` it does mark the instance as it's context is not validated in Publisher and cannot be modified by artist. Must be prefilled by create plugin, this does allow editorial create plugins to create instances before their target folder and task do exist.
I'm not sure if `"has_promised_context"` should be stored to instance data as it does not have to be stored to scene. Maybe using transient data would be more sufficient?
1. …
=> Create: Allow context promise for editorial workflow

client/ayon_core/lib/attribute_definitions.py
Some typos.
It does add an attribute `type = "ui-def"` somewhere - I wasn't sure that was reasonable in the original PR.
Ported from https://github.com/ynput/OpenPype/pull/6346
Check code changes
1. Check code changes
=> Fix attribute_definitions.py typos

client/ayon_core/pipeline/create/structures.py
Use `transient_data` over instance `data` to look for promissed context value.
Changes related to https://github.com/ynput/ayon-core/pull/880 instead of looking to instance data is looked into transient data. That causes 2 things:
1. The value is not stored to scene.
2. Create plugin has to fill it in `collect_instances`.
Previous PR already did have small discussion about it and after brief discussion with @jakubjezek001 now we've came to conclusion that it should be handled this way.
1. Validate workflow change.
=> Create Context: Use transient data for promised context

client/ayon_core/pipeline/farm/pyblish_functions.py
This occured only in Maya (or DCC with AOV), caused pasting whole absolute path to metadata.json which could cause `Given file names contain full paths` (if ValidateExpectedFiles was disabled). 'files' is expecting only file names, not full paths.
1. disable `ValidateExpectedFiles`
2. publish from Maya
3. check metadata.json, shouldn't contain absolute paths, but only file names in `files`
=> Fix: Not removing absolute path in Maya DL submission

client/ayon_core/plugins/publish/integrate_inputlinks.py, client/ayon_core/tools/loader/models/sitesync.py
When workfile representation is being downloaded with SiteSync addon, it should also download all referenced, eg loaded representations if they are not present on target site.
No need to test it in Maya, links should work in any DCC.
1. enable SiteSync addon, set studio-studio in Site Settings
1. publish workfile with something loaded via Loader
2. this should create `reference` link between workfile and loaded representation (could be checked by Node Addon??)
3. switch Site Settings to `local` - `studio` (to actually engage syncing) and set there your root folder for your local site ( restart Tray)
4. go to Loader, find published workfile from step 1 and `Download` it (bottom right corner)
5. it should eventually download both workfile and referenced representation
=> Fix: download referenced representations when synchronizing workfile via SiteSync addon

client/ayon_core/hooks/pre_ocio_hook.py, client/ayon_core/pipeline/constants.py, client/ayon_core/plugins/publish/validate_file_saved.py
Set up the OCIO env vars on launch of Cinema4D application with `ayon-cinema4d` integration.
Related to https://github.com/ynput/ayon-applications/pull/36
1. OCIO env var should be set on launching Cinema4D
=> Add cinema4d to OCIO prelaunch hook

client/ayon_core/plugins/publish/integrate.py
Integrator: Log the filepath if invalidated for being fullpath for clearer log
This makes it easier to debug logs failing due to somehow 'finding' a full path in the data.
1. Publish something that for whatever reason sets a fullpath for `instance.data["representations"][0]["files"]` or alike.
=> Integrator: Log the filepath if invalidated for being fullpath for clearer log

client/ayon_core/lib/path_tools.py, client/ayon_core/plugins/load/delivery.py
Support the `{udim}` key in delivery template to deliver UDIM sequences.
Fixes #905 
1. Publish a UDIM sequence from e.g. Substance Painter
2. Run "Deliver Versions" action to deliver the UDIMs
Use e.g. delivery template:
```json
{
"name": "udims",
"directory": "{root[work]}/{project[name]}/io_test/{yy}{mm}{dd}",
"file": "{project[code]}{asset}{subset}{@version}<{output}><.{@frame}><_{udim}>.{ext}"
}
```
=> Fix delivering UDIMs using {udim} in delivery template

client/ayon_core/pipeline/__init__.py, client/ayon_core/pipeline/constants.py
Constant `HOST_WORKFILE_EXTENSIONS` is deprecated and unused for a long time. It is time to remove it.
Workfile extensions are defined by host addons by implementing `get_workfile_extensions`.
1. Validate `HOST_WORKFILE_EXTENSIONS` is not really used.
2. Validate changes.
=> Chore: Remove 'HOST_WORKFILE_EXTENSIONS'

client/ayon_core/tools/push_to_project/models/integrate.py
Pushing a product to a library project, linking to an existing task, is currently broken. This should fix it. My guess is that some time ago, the product attribute "type" was changed to "taskType" 
1. Open the loader (standalone or in-app) and push a published product to library
2. Select a library and an existing asset
3. **Remove the "New Folder name"**, so you can select tasks
4. Select a task and hit Publish
=> Push to Library Project taskType naming bugfix

client/ayon_core/lib/transcoding.py
Ayon's OIIOtool handling currently removes all subimages (all AOVs that aren't RGBA). This PR does the following: 
- takes out the argument that restricts to 1 subimage
- modifies the colour conversion arguments to only occur on the first subimage (rgba). 
The results of the OIIOtool will be unchanged, unless the input files have >1 subimages and the OIIOtool argument "-a" is added (should this be documented somewhere?). Then, extra channels will pass through the transcode, and can have reformats etc applied if desired.
To have subimages identified, inputs must be a proper multipart EXR. In Nuke, this can be done by setting "interleave" to "channels" in the write node (very easy to define in the Ayon Nuke addon). Don't forget to set your channels to "all"!
1. Configure an Extract OIIO …
=> improved OIIO subimages handling

client/ayon_core/pipeline/editorial.py, tests/client/ayon_core/pipeline/editorial/resources/img_seq_23.976_metadata.json, tests/client/ayon_core/pipeline/editorial/test_media_range_with_retimes.py
Fixes issue reported by @jakubjezek001 on Discord when source_range and available_range rates are technically the same rate but not exactly the same value in the OTIO exported file.
1. Run the unit tests
run `.\tools\manage.ps1 run pytest .\tests\client\ayon_core\pipeline\editorial\` (windows)
run `.\tools\manage.sh run pytest .\tests\client\ayon_core\pipeline\editorial\` (linux)
=> Fix NTSC framerates floating issue comparison.

client/ayon_core/tools/publisher/models/publish.py
Remove exception from log records.
Pyblish process method is logging exception which is added to records of our custom message handler.
1. Validation error does not add error log to logs with traceback.
Resolves https://github.com/ynput/ayon-core/issues/937
=> Publisher: Remove pyblish exception log from records

client/ayon_core/pipeline/delivery.py, client/ayon_core/plugins/load/delivery.py
Delivery template data recalculates all entity keys from representation hierarchy.
It is common that representation context, with data used for publish template, does not contain all keys that can be used during delivery. For that purposes was implemented new function `get_representations_delivery_template_data` which prepares the data of representation.
We don't have very good delivery api functions, created issue for improvement https://github.com/ynput/ayon-core/issues/953 .
1. Deliver template that contains `{parent}` should be possible to use for delivery of representation that didn't have `{parent}` in publish template.
Resolves https://github.com/ynput/ayon-core/issues/929
=> Delivery: Fill hierarchy data unused during publishing

client/ayon_core/pipeline/farm/pyblish_functions.py
Fix publishing of single frame render jobs.
Why is this suddenly a new issue? It's due to this PR: https://github.com/ynput/ayon-core/pull/908
That actually fixed a long-standing bug... where a plug-in in Deadline would silently and secretly be fixing it, here: https://github.com/ynput/ayon-deadline/blob/368e2510dc3f8dc904168e51f9afa91c1428986c/client/ayon_deadline/plugins/publish/global/validate_expected_and_rendered_files.py#L74-L77
I couldn't fix this "on collect renders" for Maya - because that'd make it fail here where it still expects it to be a list: https://github.com/ynput/ayon-core/blob/e5fe964178c7fee39f8a62eda98fd5ad583a8213/client/ayon_core/pipeline/farm/tools.py#L80-L88
This likely also fixes it for other hosts that use `instance.data["expectedFiles"]` with the value being …
=> Fix single frame publishing for publish job on farm (to Deadline from e.g. Maya)

client/ayon_core/pipeline/create/structures.py
Added implementation to iterate over `AttributeValues`.
`AttributeValues` should behave as dict but iterating over it does not behave the same way.
1. If is possible to iterate over `AttributeValues` object to get keys.
Resolves https://github.com/ynput/ayon-core/issues/804
=> Create Attribute values: Implemented iter

client/ayon_core/lib/attribute_definitions.py
TextDef can be serialized if does not have defined regex pattern.
1. Create `TextDef` object without `regex` and call `clone`.
2. It should not crash.
=> Attribute defs: Fix serialize of text wihout regex

client/ayon_core/plugins/publish/extract_hierarchy_to_ayon.py
Preparation for upcoming changes in ayon api EntityHub.
Use explicit kwargs to fill task type and folder type.
I really don't know exact steps.
1. Creation of new folders and tasks during editorial publishing should work as before.
=> Editorial: Prepare for new args and kwarg in EntiyHub

client/ayon_core/pipeline/delivery.py
Fixed bug caused by ayon api which did not fully convert representation entity data in `get_representations_hierarchy`.
The issue is already fixed in newer version of ayon api 1.0.10 (AYON launcher 1.1.1). But added this fix for those who still use older versions.
```
File "C:\Users\...\AppData\Local\Ynput\AYON\addons\core_1.0.3\ayon_core\plugins\load\delivery.py", line 210, in deliver
get_representations_delivery_template_data(
File "C:\Users\...\AppData\Local\Ynput\AYON\addons\core_1.0.3\ayon_core\pipeline\delivery.py", line 386, in get_representations_delivery_template_data
template_data.update(copy.deepcopy(general_template_data))
AttributeError: 'str' object has no attribute 'update'
```
1. Use AYON launcher 1.1.0 to run delivery action.
2. It …
=> Delivery: Fix representation entity data

client/ayon_core/pipeline/create/context.py
Create context has helper functions to collect and cache entities.
The need came with https://github.com/ynput/ayon-deadline/pull/49 . That PR is fetching entities on each instance change which slows down the whole logic a lot. This way the entities are cached on CreateContext which avoids unnecessary re-fetching of the same data. The PR needed specifically task type, but I guess there will come soon more that will want to use attributes etc.
The methods are using folder path and task name for filtering as that is what instances have available in data.
The same methods are not used for context validation and to get current context entities.
1. All should be ok when publisher UI is opened in any host.
2. Validation of context should still happen without any issues.
3. Invalid context on …
=> Create Context: Helper function to get entities

client/ayon_core/lib/log.py
Remove `Logger.mongo_process_id`
Was once used a long time ago in ftrack services back in OpenPype era?
1. Logger should work
2. Addons should still work (esp. ftrack)
=> Remove `Logger.mongo_process_id`

client/ayon_core/style/data.json, client/ayon_core/style/style.css, client/ayon_core/tools/publisher/abstract.py, client/ayon_core/tools/publisher/models/create.py, client/ayon_core/tools/publisher/widgets/product_attributes.py
Visualy display if value of attributes on instance does not match default value.
It should also behave correctly on multiselection of instances even if they don't have same default values. But if at least one of selected instances does not use default value it is shown as overriden.
1. Open Publisher in host of your choice.
2. Create an instance (or use existing one).
3. Change any attribute value.
4. It should change color of it's label.
Resolves https://github.com/ynput/ayon-core/issues/139
=> Publisher: Display overridden vs default values of attributes

client/ayon_core/style/style.css, client/ayon_core/tools/attribute_defs/__init__.py, client/ayon_core/tools/attribute_defs/_constants.py, client/ayon_core/tools/attribute_defs/files_widget.py, client/ayon_core/tools/attribute_defs/widgets.py, client/ayon_core/tools/publisher/abstract.py, client/ayon_core/tools/publisher/control.py, client/ayon_core/tools/publisher/models/create.py, client/ayon_core/tools/publisher/widgets/product_attributes.py
Implemented context menu option on attribute definitions to reset attribute values to default states.
All attribute definition widgets should have implemented logic to be able to reset value of attributes to default value. In Publisher it does reset to default value per instance.
1. Open Publisher in host of your choice.
2. Create instance/s.
3. In Publish tab select instance/s and change their values.
4. When you right click them and choose `Revert to default` it should set value to default value defined by create/publish plugin. It should also work on multiselection.
=> Publisher: Revert to default value

client/ayon_core/tools/publisher/widgets/product_attributes.py
Fixed conditions triggering refresh of values in UI.
I've noticed that the condition that should trigger refresh of values in UI has opposite condition to what it should be. Both create and publish attributes should be updated if happened changes in those keys.
As far as I know this feature is not used at this moment. It should be possible to fake it. For example in Create plugin, register listen to value changes and make sure instance has 2 checkboxes, when checkbox 1 changes value, also change value of checkbox 2 to the same value in the callback. That change done by create plugin should be propagated to UI.
=> Publisher: Refresh of create/publish values under correct conditions

client/ayon_core/lib/attribute_definitions.py
Small enhancement in attribute definitions.
I got lost a little when I was developing something related attribute definitons lately, during that time I've added typehints so I don't have to go back and forth. The original PR is merged so not I though I'll create PR adding the typehints.
1. Make sure it makes sense.
Resolves https://github.com/ynput/ayon-core/issues/993
=> Chore: Add type hints to attribute definitions

client/ayon_core/plugins/actions/open_file_explorer.py
Explore here launcher action does work on macOs.
- As suggested by @BigRoy (see [here](https://stackoverflow.com/a/3520693)), use `open -R` instead of `open -na` for opening a folder using the explorer.
---
1. Open AYON Launcher
2. Browse folders
3. Use `Explore here`
Resolves https://github.com/ynput/ayon-launcher/issues/183
Resolves https://github.com/ynput/ayon-core/issues/964
=> Use open -R for opening explorer on MacOS

client/ayon_core/tools/sceneinventory/model.py, client/ayon_core/tools/sceneinventory/models/containers.py
Filter to outdated works again in scene inventory.
1. Open host of your choice.
2. Open loader.
3. Load some representations that are **not** from latest version and some that are from latest version.
4. In Scene manager check `Filter to outdated`.
5. It should keep only those that are outdated.
Resolves https://github.com/ynput/ayon-core/issues/886
=> Scene manager: Filter to outdated toggle does work

client/ayon_core/lib/attribute_definitions.py
Fix issues connected to calling `from_paths` with invalid arguments.
Pass to `from_paths` all required arguments.
Validate the changes in code.
1. Create `FileDef` with default value set to a path (`FileDef(..., default=["/path/to/file"])`).
2. It should not crash.
Resolves https://github.com/ynput/ayon-core/issues/991
=> Attribute definitions: Fix FileDef value conversions

client/ayon_core/tools/attribute_defs/widgets.py
Fix Attribute Definitions for Loader options
Fixes:
```python
File "F:\dev/ayon-core/client\ayon_core\tools\loader\ui\products_widget.py", line 351, in _on_context_menu
result = show_actions_menu(
File "F:\dev/ayon-core/client\ayon_core\tools\loader\ui\actions_utils.py", line 61, in show_actions_menu
selected_options = _get_options(action, selected_action_item, parent)
File "F:\dev/ayon-core/client\ayon_core\tools\loader\ui\actions_utils.py", line 89, in _get_options
dialog = AttributeDefinitionsDialog(options, parent)
File "F:\dev/ayon-core/client\ayon_core\tools\attribute_defs\dialog.py", line 10, in __init__
attrs_widget = AttributeDefinitionsWidget(attr_defs, self)
File "F:\dev/ayon-core/client\ayon_core\tools\attribute_defs\widgets.py", line 159, in …
```
=> Fix loader load option box widgets

client/ayon_core/tools/tray/lib.py
Tray is not trying to kill other than AYON processes.
Implemented function that collects command line arguments of the running process. Based on the executable name detects if the process is AYON process.
1. Be on Windows.
2. Start tray.
3. Go to `%LOCALAPPDATA%\Ynput\AYON\tray`, there should be one file.
4. Duplicate the file with some prefix (e.g. `_`).
5. Close tray.
6. Go to `%LOCALAPPDATA%\Ynput\AYON\tray` and rename the file to origin name.
7. Start any application you'd like (other than AYON).
8. In task manager find PID of the process (I chose Notepad which in my case have PID 29780).
9. Modify the file and change pid to pid of your application.
10. Start tray again.
11. Your application should not be closed and tray should start.
Resolves …
=> Tray: Don't kill other processes

client/ayon_core/vendor/python/scriptsmenu/action.py, client/ayon_core/vendor/python/scriptsmenu/launchformaya.py
Fix support of scripts menu in Qt6, e.g. Maya 2025.
This initially tried to fix it https://github.com/ynput/ayon-core/pull/669 however it did fix the "startup" error but it did make it fail to trigger the actual command from the menu entry due to the callback check when running a menu entry.
1. Launch Maya 2025
2. Run an action from the Custom Tools menu
This should also be backwards compatible in older Python versions, so also test e.g. Maya 2022, 2023 or 2024.
I personally tested on Windows in Maya 2022.3, Maya 2024.2 and 2025.3.
=> Fix support for scriptsmenu running commands in PySide6

client/ayon_core/pipeline/create/structures.py, client/ayon_core/tools/publisher/models/create.py
Added required keys for `CreatedInstance`, required keys are meant to make sure instance data contains the key, even if someone tries to remove them, or is not passing them on initialization.
All the keys are not really mandatory for instance to exist, but most of logic expects them to be set and available. Also fixed immutable key name `product_type` > `productType`.
We should define those keys with setters/getters with typehints.
1. It is possible to initialize `CreatedInstance` without `"folderPath"` and `"task"` but `instance["folderPath"]` and `instance["task"]` can be used (returns `None`).
=> Create: Required keys in Create Instance data

client/ayon_core/tools/loader/ui/products_delegates.py
Product/version selection does not change on hover over version combobox.
It looks like views do change selection based on focus and having available editor widget. It skips that logic if editor has `NoFocus` policy. Based on documentation they should have set focus policy ti `NoFocus` as we don't want to be able to "focus" into the widget.
1. Hover over version combobox does not change selection of products in loader tool.
2. It is possible to change version in loader tool ->this should be probably tested in Qt native DCC (e.g. maya) and some non-native DCC (e.g. blender).
Resolves https://github.com/ynput/ayon-core/issues/1007
=> Loader UI: Don't change selection on version combobox hover

client/ayon_core/plugins/publish/collect_otio_review.py, client/ayon_core/plugins/publish/collect_otio_subset_resources.py, client/ayon_core/plugins/publish/extract_color_transcode.py, client/ayon_core/plugins/publish/extract_colorspace_data.py, client/ayon_core/plugins/publish/extract_otio_review.py
Editorial supports distribution of colorspace data within editorial otio media resources and reviewable clips.
Within the scope of https://github.com/ynput/ayon-hiero/issues/22
This needs to be tested together with https://github.com/ynput/ayon-hiero/pull/23
1. all should work as it was, but colorspace in editorial is now distributed
=> Editorial: Distribution of colorspaceData within instance resources and reviewables

client/ayon_core/pipeline/publish/publish_plugins.py
Show publish plug-in attributes based on `families` instead of only `productType`
This PR can be tested together with https://github.com/ynput/ayon-houdini/pull/144
This PR split off from this one https://github.com/ynput/ayon-core/pull/973 so it only contains the tiny change.
This commit https://github.com/ynput/ayon-core/commit/8208bef6f31933a1b0aef5151dc2b957e712fe03 allows to show publish plugin attributes also based on the created instance `families` data instead of only the product type. As such, if the Creator defines extra families - then the Pyblish plug-ins for which it will run will now also show their publisher attributes.
This is a required change to easily start supporting a workflow where we can target particular instances from plug-ins without having to target the product …
=> Show publish plug-in attributes based on `families` instead of only `productType`

client/ayon_core/addon/base.py, client/ayon_core/cli.py, client/ayon_core/lib/attribute_definitions.py, client/ayon_core/lib/local_settings.py, client/ayon_core/pipeline/create/context.py, client/ayon_core/pipeline/create/product_name.py, client/ayon_core/pipeline/editorial.py, client/ayon_core/pipeline/entity_uri.py, client/ayon_core/pipeline/farm/pyblish_functions.py, client/ayon_core/plugins/publish/collect_hierarchy.py, client/ayon_core/plugins/publish/extract_otio_review.py, client/ayon_core/plugins/publish/validate_unique_subsets.py, client/ayon_core/scripts/otio_burnin.py, client/ayon_core/settings/lib.py, client/ayon_core/tools/creator/widgets.py, client/ayon_core/tools/launcher/models/actions.py, client/ayon_core/tools/loader/ui/_multicombobox.py, client/ayon_core/tools/loader/ui/products_model.py, client/ayon_core/tools/publisher/widgets/overview_widget.py, client/ayon_core/tools/publisher/widgets/product_context.py, client/ayon_core/tools/publisher/widgets/tasks_model.py, client/ayon_core/tools/publisher/window.py, client/ayon_core/tools/sceneinventory/models/containers.py, client/ayon_core/tools/utils/lib.py, pyproject.toml, server/settings/publish_plugins.py, server/settings/tools.py, tests/client/ayon_core/pipeline/editorial/test_extract_otio_review.py
Ruff config is now stricter and reports all linting errors.
Fixed/modified all places that were reported by ruff.
1. Look at code changes.
2. Verify code changes.
=> Chore: Stricter ruff config

client/ayon_core/plugins/publish/collect_anatomy_instance_data.py
Use `folderPath` to calculate `hierarchy` instead of requiring `hierarchy` on instance data.
The hierarchy was required from OpenPype but with AYON we already have it available on `folderPath`.
1. Editorial instances don't have to fill `hierarchy` on instance to be integrated.
=> Editorial: Don't require 'hierarchy' key on instance

client/ayon_core/pipeline/publish/__init__.py, client/ayon_core/pipeline/publish/constants.py, client/ayon_core/plugins/publish/collect_farm_env_variables.py
Moved some of logic to define farm job environment variables from ayon-deadline to ayon-core.
There already is plugin https://github.com/ynput/ayon-deadline/blob/develop/client/ayon_deadline/plugins/publish/global/collect_deadline_job_env_vars.py that is collecting environment variables, but that is not extedable because the constant defined in deadline should be supplied from ayon core, and most of the variables defined in the plugin should be defined by ayon-core, ayon-ftrack, ayon-shotgrid or ayon-applications addon. This is first step to be able to actually do it in the other plugins. Right now they would have to import from ayon-deadline and have dependency to ayon-deadline addon.
This PR also will take effect only with changes in this PR …
=> Chore: Set environment variables for farm

client/ayon_core/plugins/publish/extract_otio_audio_tracks.py
This resolves https://github.com/ynput/ayon-hiero/issues/32
The audio extraction code hasn't been updated since the recent work to fix embedded timecode detection and media available range computation. These changes ensure that OTIO audio extraction properly works for updated and non-updated OTIO exporters.
1. Prepare a timeline in Hiero with audio tracks
2. Ideally you'll want to use medias with embedded timecodes
3. Publish audio clip(s) from this timeline 
4. Ensure that resulting audio products match the different clip(s) from the timeline
=> Fix audio extraction from OTIO timeline.

client/ayon_core/plugins/publish/collect_farm_env_variables.py
Actually collect valid values for farm environment variables.
The plugin did use values from os.environ but most of the values are not set in env variables, or it should not be based on env variables.
- AYON_USERNAME - is not filled in os.environ
- AYON project/folder/task - should be filled from context data instead of os.environ
- AYON_LOG_NO_COLORS - should be forced to be `"1"` for farm
1. The values under farm key are correct.
=> Farm env: Collect correct values for farm

client/ayon_core/plugins/publish/extract_otio_review.py
Minor fix, ensure `extract_otio_review` is skipped when no OTIO clip is available.
This fixes the following issue:
=> Fix extract_otio_review

client/ayon_core/plugins/publish/collect_otio_subset_resources.py
These changes fixes the bug for Hiero, Flame and Resolve where we realized that the [Clip media] option of Reviewable Source did not work properly.
See https://github.com/ynput/ayon-hiero/pull/38 for more details.
This changes needs to be tested alongside https://github.com/ynput/ayon-hiero/pull/38
1. Open Hiero and create instance(s) through the `Create Publishable Clip`
2. Set the review source media to `[Clip media]`
3. Publish and ensure that the resulting review product is created from the original clip media entire range (untrimmed)
AY-7242
=> AY-7242_Implement review representations in OTIO subset resources.

client/ayon_core/tools/loader/control.py, client/ayon_core/tools/sceneinventory/models/containers.py
Loader and scene inventory should not cause issues when container in scene contains invalid representation id.
Capture all possible errors when validating representation ids. In case of Loader tool, we really need only the representation ids and we don't care about anything else. In scene inventory already happens some validation of the data. The validation does not fully preserve issues, but that probably should not be job of the tool.
Partially resolves https://github.com/ynput/ayon-core/issues/788 . The issue is more aboud full validation of container data, which might be actually production breaking change at this moment as we don't enforce container schema now. And it might be more work than a simple capture of unhandled exceptions. We do miss a lot of load related api, which is epic …
=> Loader & Scene inventory: Ignore containers with invalid representation id

client/ayon_core/pipeline/farm/pyblish_functions.py
Solves bug where Deadline now ignores Nuke slate, and offsets the published exr sequence.
Solves https://github.com/ynput/ayon-deadline/issues/73
1. setup Nuke workfile with slate, publish in DL
2. same setup publish locally
3. both `publish` version folders should contains same amount of files
=> Fix missing slate frame in Deadline publish

client/ayon_core/pipeline/workfile/path_resolving.py
Use `taskType` instead of `type` key from task entity.
Also added some typehints to the function.
1. Add new template to workfile templates in project anatomy, make sure the template is "different" from default one (e.g. add `/test` in the middle of directory path).
2. Change `ayon+settings://core/tools/Workfiles/workfile_template_profiles` so it uses `default` template by default and the new template for task type of your choice (e.g. `Modeling`).
3. Run DCC on task with used task type.
4. The template from step 1. should be used instead of default for workfile path.
Resolves https://github.com/ynput/ayon-core/issues/1029
=> Chore: Workfile template name filters by correct task type

client/ayon_core/pipeline/tempdir.py, client/ayon_core/plugins/publish/collect_otio_subset_resources.py, client/ayon_core/plugins/publish/extract_otio_review.py
Resolve https://github.com/ynput/ayon-resolve/issues/44
* Ensure `ayon-core.pipeline.tempdir.create_custom_tempdir` is still exposed but flagged as backward compatible.
This function is not officially exposed in the `__init__.py` but directly called from within resolve:
https://github.com/search?q=org%3Aynput+create_custom_tempdir&type=code
* Ensure extract OTIO review does not expect handle values when no otioClip is set
Testing procedure through Resolve is here: https://github.com/ynput/ayon-resolve/pull/46
=> AY-7222 Fix otio_review no handles and tempdir for Resolve

client/ayon_core/addon/base.py, client/ayon_core/addon/interfaces.py, client/ayon_core/tools/launcher/models/actions.py, client/ayon_core/tools/launcher/ui/window.py
Show all addon actions.
Fixing bug caused by https://github.com/ynput/ayon-core/pull/1044.
1. Create package, upload ad use in bundle.
2. Start AYON launcher and open Launcher.
3. Select a context.
4. Actions from all addons should be shown, not just applications.
Resolves https://github.com/ynput/ayon-core/issues/1055
=> Launcher: Addon actions are shown

client/ayon_core/pipeline/context_tools.py
Always increment workfile when requested - instead of only when no unsaved changes
Fixes https://github.com/ynput/ayon-blender/issues/86
But also changes the same behavior for Maya and Blender.
1. Version up workfile menu entry should increment workfile even when no unsaved changes
=> Increment workfile even when no unsaved changes

client/ayon_core/pipeline/publish/lib.py, client/ayon_core/pipeline/staging_dir.py
Store in instance data whether the staging dir set is a custom one
Required to fix issue https://github.com/ynput/ayon-maya/issues/194#issuecomment-2556797055 using PR https://github.com/ynput/ayon-maya/pull/204
I did wonder a bit as well whether it may have been nicer to begin with to actually store the `StagingDir` class instance on the `instance.data` instead of the individual separate keys like we're doing now. But also felt that if we do want to - it may be better refactoring that separately.
1. Test with https://github.com/ynput/ayon-maya/pull/204
2. Submitting renders should work as intended with both custom staging dir set and when disabled.
=> Store in instance data whether the staging dir set is a custom one

client/ayon_core/host/dirmap.py
Remove host name separator in dirmap settings, so that [Maya settings `maya_dirmap` or `maya-dirmap` is now `dirmap` inside that host's settings.](https://github.com/ynput/ayon-maya/blob/d0a8fc35662196ef3e468d3eca4e939be3071a91/server/settings/main.py#L54-L55)
Only other integration I can see that has dirmapping is [Nuke, which uses just `dirmap` without host prefix](https://github.com/ynput/ayon-nuke/blob/a1a0f14bff445dda1de083b47b8a0c143d774dbd/server/settings/main.py#L60-L63) - which I suppose would then be broken regardless anyway but I think [it uses its own way of remapping paths](https://github.com/ynput/ayon-nuke/blob/e401649b044c708d38f31d387e8e1955c4c289e4/client/ayon_nuke/api/pipeline.py#L171-L174). It may make more sense to remove the `host` specific prefix from the label …
=> AY-6502_Fix Maya dirmap settings

client/ayon_core/tools/launcher/ui/actions_widget.py
In tray launcher, fix red dot for FORCE_NOT_OPEN_WORKFILE_ROLE to be drawn on wrong location if app is not on first row
In the launcher the "Skip open last workfile" red dot on the applications draws in the wrong location if the app is on the second line (e.g. not top row)
In this case the Maya is set to skip last workfile, even though the red dot is still drawn as if that app was at the top row.
This PR fixes it. Now it becomes:
1. Force disable/enable the open last workfile via right mouse click
2. Shrink width of the launcher so the app ends up on second row.
3. The drawn red dot should look ok.
=> Launcher: Fix red dot for FORCE_NOT_OPEN_WORKFILE_ROLE to be drawn on wrong location if app is not on first row

client/ayon_core/lib/path_templates.py
resolve #1059 
`Anatomy.format_all` is failing with unpadded int raises when attempting to convert `int` to `TemplatePartResult`
A work-around was to edit the problematic template with a padded int this is the proper code fix.
Fix discussed with @iLLiCiTiT 
1. Add the following template into your project `Anatomy`
```
default_test
{root[work]}/{project[name]}/OUT/DELIVERY/{yyyy_mm_dd}/{product[name]}/{@version}
{originalBasename}_{studio[name]}_{yyyy-mm-dd}_{version}.{ext}
```
2. Either run a publish to trigger `extract_burnins` or run the following
```python
from ayon_core.pipeline import Anatomy
anatomy = Anatomy("Dummy")
formatted = anatomy.format_all({"version": 5})
```
3. It failed before the fix, it should not fail anymore after.
=> Fix Anatomy.format_all with unpadded int values.

client/ayon_core/pipeline/create/creator_plugins.py, client/ayon_core/pipeline/publish/lib.py, client/ayon_core/pipeline/staging_dir.py
Added typehints. Function `get_staging_dir_info` returns `StagingDir` instead of string.
Change bool attribute names to have `is_` prefix.
Also changed key `stagingDir_custom` to `stagingDir_is_custom`. I would like to use `stagingDirIsCustom` but there were opinions against that would not match existing `stagingDir_persistent` which cannot be changed because of backwards compatibility.
Attribute `is_persistent` has backwards compatibility to still support `persistent` even tho it is not used anywhere else. Key `stagingDir_persistent` cannot be changed at this moment, because it would break backwards compatibility. We could support both keys, but I have no idea how it is being used at other addons (e.g. if it is being changed?).
Function `get_staging_dir_info` could be maybe cleaned up a …
=> Chore: Staging dir enhancements

server/settings/publish_plugins.py
resolve #1081 
New default values follow: 
https://github.com/ynput/ayon-core/blob/a141237650951354005000c77e50e250198f35af/client/ayon_core/plugins/publish/extract_usd_layer_contributions.py#L275-L276
1. everything should work as before, I've only updated the default values in settings.
=> Update default order to match values in `CollectUSDLayerContributions`

client/ayon_core/pipeline/create/creator_plugins.py
Following https://github.com/ynput/ayon-core/pull/1069 and testing https://github.com/ynput/ayon-nuke/pull/52, I realized `apply_staging_dir` was missing `stagingDir_is_custom`.
The following ensure Nuke product can be published with custom staging directories.
1. Enable custom staging directory with some profiles ayon+settings://core/tools/publish/custom_staging_dir_profiles (make it persistent so you can troubleshoot)
2. Create a template matching the staging directory under ayon+anatomy://Dummy/templates/staging
e.g. {root[work]}/{project[name]}/{hierarchy}/{folder[name]}/temp_render_only/{product[type]}/{product[name]}
3. Open Nuke and create+publish some products
4. Ensure that the staging directory is working is properly redirected to the relevant template for the associated …
=> Report stagingDir_is_custom to apply_staging_dir

client/ayon_core/tools/workfiles/widgets/files_widget.py
Only allow saving and browsing from a "task" context.
Fixes e.g. this error when clicking Save As before the Workfiles tool has fully initialized:
```
File "C:\CODE\__YNPUT\ayon-core\client\ayon_core\tools\workfiles\widgets\files_widget.py", line 253, in _on_workarea_save_clicked
result = self._exec_save_as_dialog()
File "C:\CODE\__YNPUT\ayon-core\client\ayon_core\tools\workfiles\widgets\files_widget.py", line 175, in _exec_save_as_dialog
dialog.update_context()
File "C:\CODE\__YNPUT\ayon-core\client\ayon_core\tools\workfiles\widgets\save_as_dialog.py", line 254, in update_context
self._extension_combobox.addItems(data["extensions"])
TypeError: 'PySide2.QtWidgets.QComboBox.addItems' called with wrong argument types: …
```
=> Workfiles: Browse and Save As button only enabled when in valid context

client/ayon_core/hooks/pre_add_last_workfile_arg.py, client/ayon_core/hooks/pre_ocio_hook.py, client/ayon_core/pipeline/farm/pyblish_functions.py, client/ayon_core/plugins/publish/collect_resources_path.py
Add substance designer as being part of the hosts for OCIO and last workfile prelaunch hook.
Use together with the related application addon https://github.com/ynput/ayon-applications/pull/50 and initial integration
1. Build and install core addon
2. Last workfile can be launched as expected.
=> Add substance designer support

client/ayon_core/tools/workfiles/widgets/window.py
Of all the AYON UIs, the workfiles tool was the only one that relatively had big margins around its full layout:
This PR reduces that to:
For comparison, some other tools:
Loader:
Publisher:
Scene Inventory:
1. Workfiles tools should look better
=> Reduce margins on Workfiles tool due to nested layouts

client/ayon_core/pipeline/create/legacy_create.py, client/ayon_core/pipeline/create/structures.py
Use `AYON_INSTANCE_ID` constant by default for new instances instead of deprecated `AVALON_NSTANCE_ID`.
This might affect hosts that don't load `AYON_INSTANCE_ID` but still uses `AVALON_NSTANCE_ID`, hopefully there is none.
1. Create plugins in all hosts should be able to collect existing instances.
2. Create plugins in all hosts should be able to create new instances, that are then collected.
=> Create: Use 'AYON_INSTANCE_ID' by default instead of 'AVALON_NSTANCE_ID'

server/settings/publish_plugins.py
Add Silhouette host to defaults of version and outdated containers validators
Relates to `ayon-silhouette`
1. Settings should be the new defaults.
=> Add Silhouette host to defaults of version and outdated containers validators

client/ayon_core/style/style.css, client/ayon_core/tools/publisher/widgets/report_page.py
Report page can be stretched so long logs should be accessible.
Set minimum size of content widget to be able to stretch it's size.
1. Long logs on Report page can be readable.
=> Publisher: Report page can stretch logs

client/ayon_core/pipeline/create/structures.py
It is possible to set transient data on instance creation.
Create plugins cannot fill attribute definitions on instance initialization, if their logic is based on transient data.
1. Validate code changes.
=> Create: Allow to pass in transient data on instance creation

client/ayon_core/plugins/publish/collect_otio_review.py, client/ayon_core/plugins/publish/collect_otio_subset_resources.py, client/ayon_core/plugins/publish/extract_otio_review.py
While working on retimes, I realized I've over-engineered the logic to handle `[clip_media]` reviewable.
When selected the reviewable should be `otio_clip` original media source range + handles.
This change simplify the approach to make it leverage `collect_otio_review`, `extract_otio_review` and `extract_review`.
Changes:
1. From Flame or Hiero publish shot clip with the `[clip_media]` reviewable enabled
2. Ensure reviewable is properly produce from clip source range (no retime applied) + handles
=> Fix [clip_media] reviewable.

client/ayon_core/pipeline/publish/publish_plugins.py
When `optional_tooltip: str` attribute is found on the publish plugin that inherits from `OptionalPyblishPluginMixin` and the plug-in is optional, then this tooltip will be added to the checkbox in the publisher UI.
Not sure if there's a nicer way - but there were just cases where I figured having some tooltip could be nice to clarify specific optional toggles.
Would it be nice to have `optional_tooltip: Optional[str] = None` attribute default on `OptionalPyblishPluginMixin`? For better auto-complete?
1. Add `optional_tooltip` string attribute to optional plug-in that inherits from `OptionalPyblishPluginMixin`
2. The tooltip should show on the attribute definition for the checkbox.
=> Add support for `optional_tooltip` attribute on `OptionalPyblishPluginMixin`

client/ayon_core/lib/path_templates.py
List values are correctly resovled as have missing index/key.
The validation was not readable much and it was looking at length of input data instead of lenght of current value.
1. Use `<{folder[parents][100]}>` in anatomy template.
2. Run some process to try fill the template.
3. It should not crash because of `IndexError`.
=> String template: Fix index validation for list values

client/ayon_core/pipeline/create/context.py
Helper method to preare template data for passed folder path and task name.
It looks like it is common to prepare template data for given context which requires a lot of preparations inside create plugins, this should help to avoid that with single call.
1. The reason why this method was added makes sense.
2. The method does what should do.
=> Create: Add helper 'get_template_data' to create context

client/ayon_core/pipeline/create/creator_plugins.py
Auto fill project entity from current context if is not passed into the create plugin method.
There is low chance we will call this method from different than current project, but I've added check for the project name (just safety).
1. Product name calculation might be a little bit faster for creators which are calling the method on their own (e.g. auto-creators).
=> Create: Auto-fill project entity in get product name if is not passed in

client/ayon_core/lib/execute.py
Escape & on Windows in shell using ^& in `run_subprocess`
Fix https://github.com/ynput/ayon-maya/issues/231
I'm not sure if in Windows you can override the default shell somehow - if so, then the escaping may need to check for that edge case if the other shell may not use `&` as a special character.
1. Follow publishing steps of https://github.com/ynput/ayon-maya/issues/231
2. Regular publishing should continue to work
=> Escape & on Windows in shell using ^& in `run_subprocess`

client/ayon_core/plugins/publish/extract_thumbnail.py
Supports to extract thumbnail for substance designer
Resolve https://github.com/ynput/ayon-substance-designer/issues/8
n/a
1. Build and install addon
2. Launch SD and create textures
3. Publish
=> Add substance designer as being part of the hosts in extract thumbnail

.github/workflows/pr_linting.yml
This is updating ruff action on GItHub to official and maintained.
Linting on Github should work as usual
Closes #985
=> Update ruff action

client/ayon_core/tools/utils/nice_checkbox.py
NiceCheckbox does use odd sizes for frame to paint to avoid cropped paint.
It looks like it dependends where is the checkbox painted and how much space it gets, which might be based on UI scaling too. 
Requires to be able to achieve the issue on machine which might be tricky. It works ok on my 100% scaling monitor and changes on 150% scaling monitor on my work laptop, but also doesn't work on different machine with 100% scaling, so hard to tell how to replicate.
1. The checkbox is not cropped.
=> UI: Nice checkbox uses odd sizes

client/ayon_core/lib/attribute_definitions.py, client/ayon_core/tools/attribute_defs/widgets.py, client/ayon_core/tools/publisher/widgets/precreate_widget.py
EnumDef does not require to have items.
It is valid option to have empty items for multiselection enumerator.
1. It is possible to create EnumDef with empty items (e.g. in pre-create attributes).
2. It shows correctly in UI.
```python
EnumDef(
"some_key",
[],
multiselection=True,
)
```
Resolves https://github.com/ynput/ayon-core/issues/810
=> Attribute definitions: Multiselection EnumDef allows empty items

client/ayon_core/tools/common_models/hierarchy.py, client/ayon_core/tools/utils/tasks_widget.py
Use task label in UIs if is set on entity.
Before this PR only task name was shown in UIs and label was ignored.
1. Set label on task to something else from name.
2. Open UI showing tasks (e.g. launcher).
3. The task should show the label set on entity.
Resolves https://github.com/ynput/ayon-core/issues/1004
=> Tools: Use task label if is set

client/ayon_core/pipeline/create/context.py
Failed initialization of create plugin does not fail whole create context.
This is quick fix to avoid full crash of the publisher making it unusable. Created issue for better handling https://github.com/ynput/ayon-core/issues/1160.
1. If create plugin fails on initialization it should not cause fail of whole create context (and publisher UI).
=> Create context: Ignore failed initialization of create plugin

client/ayon_core/plugins/publish/extract_usd_layer_contributions.py, server/settings/publish_plugins.py
Allow setting the default USD Contribution enabled state per profile in settings
Fix #1171 
1. Change default enabled state for an entry in settings: `ayon+settings://core/publish/CollectUSDLayerContributions/profiles`
2. Default state in publisher UI should reflect the same:
=> Allow setting the default USD Contribution enabled state per profile

client/ayon_core/pipeline/farm/pyblish_functions.py
Use different varible name for aov frames.
`frames_to_render` variable was rewritten after first loop which broke next loop.
1. Submit should not crash when multiple aovs are created.
=> Publish: Render frames calculation fix

client/ayon_core/lib/python_module_tools.py, client/ayon_core/pipeline/publish/lib.py, client/ayon_core/tools/publisher/models/publish.py
When plugin is using type annotations and dataclasses, it crashed during discovery. This PR is fixing that (and possibly other type hint related issues). Closing #1199 
This PR can possibly affect how plugins are discovered so careful testing is needed.
Create plugin which is using dataclass and type annotations. Something like this:
```python
"""Test dataclass in publish plugin."""
from __future__ import annotations
from dataclasses import dataclass
from typing import ClassVar
import pyblish.api
@dataclass
class TestPublishData:
"""Test dataclass in publish plugin."""
id: str
name: str
description: str
version: str
class TestPublishPlugin(pyblish.api.ContextPlugin):
"""Test publish plugin."""
label = "Test Publish Plugin"
families: ClassVar[list[str]] = ["*"]
def process(self, context: …
```
=> Fix publish plugin discovery

client/ayon_core/tools/utils/widgets.py
Ceil height of `ExpandingTextEdit` as it returns float that might be e.g. `0.1` which might cause issues in `QSize`.
Type `float` is "invalid" type for `QSize` in some PySide releases, and I think it might fix issue with fast changes of the height in publisher report.
There is not much to test.
=> Utils widgets: Ceil height of 'ExpandingTextEdit'

client/ayon_core/tools/utils/projects_widget.py
Launcher: Make project filter field case insensitive
1. Make filter text field for projects case insensitive
=> Launcher: Make project filter field case insensitive

client/ayon_core/tools/loader/ui/product_types_combo.py
Reinstate support for python 3.7 in loader tool. Type annotation is using features unsupported in 3.7 so we need to add compatibility import.
Loader tool should open fine in python 3.7 based hosts
=> Fix: add python 3.7 support to loader tool again

client/ayon_core/pipeline/thumbnails.py, client/ayon_core/tools/common_models/thumbnails.py, client/ayon_core/tools/loader/abstract.py, client/ayon_core/tools/loader/control.py, client/ayon_core/tools/loader/ui/window.py
Artists can receive thumbnails from AYON server.
Used function to receive thumbnails does not work for artists because of ACL. That was replaced by using direct entity access which does solve ACL issue.
1. Log in as artist user.
2. Open browser/loader tool.
3. You should see thumbnails.
Resolves https://github.com/ynput/ayon-core/issues/1227
=> Tools: Change how thumbnails are received

client/ayon_core/pipeline/create/context.py, client/ayon_core/pipeline/create/structures.py
It is possible to set publish plugin value if does not have attribute definitions defined yet.
The use-case is conversion of attribute values from old plugin name to new plugin name.
1. It is possible to set values for plugin which does not have set attribute definitions yet.
Source issue came up here: https://github.com/ynput/ayon-houdini/pull/245#discussion_r2024208074
=> Create context: Set publish attributes values

client/ayon_core/tools/common_models/thumbnails.py
Always return the same output when receiving thumbnails.
1. Loader does not crash if nothing is selected, or if all selected entities don't have thumbnails.
=> Tools: Fix thumbnails output value type

.github/workflows/pr_linting.yml
Update ruff CI action on GitHub and  make it use ruff version defined in the pyproject.toml file to match what is used for linting on the client side.
Linting on GH should still work, it should use the same version as defined in pyproject.toml (hard to test because the version isn't printed anywhere.
=> Update ruff action and take the ruff version from pyproject

client/ayon_core/plugins/publish/integrate.py
Fixes a bug where the instance staging directory was being incorrectly used
when looking up the original directory for publish in place workflows,
instead of the staging directory from representation.
Adds debug logging to inspect instance data during integration.
1. create publish category anatomy template (bellow is the item data)
2. go to `ayon+settings://core/tools/publish/template_name_profiles` and create profile pointing at the anatomy publish preset. Set it to any of product you prefer to be published.
3. Add testing data to your testing project root (at least at your desired project root folder)
4. publish from your dcc or traypublisher with the matching product and host filtering at the template preset.
5. See that your data were ingested without copying into a context publish …
=> Fixes issue with original directory lookup

client/ayon_core/plugins/publish/extract_thumbnail.py
Make sure multiple reviewable representations which are requiring own thumbnail are supported by integrator.
Moves the `thumbnail_created` flag initialization inside the loop.
This ensures that the flag is reset for each representation, preventing it from being incorrectly skipped if a previous representation failed to create a thumbnail.
1. Use nuke ideally for the case.
2. create multiple reviewable intermendiate presets here `ayon+settings://nuke/publish/ExtractReviewIntermediates/outputs`
3. this should not be blocked be integrate publishing plugin crash.
=> Fixes thumbnail creation logic

client/ayon_core/plugins/publish/extract_thumbnail.py
Use out of loop variable to store information if thumbnail was created to log correctly if thumbnail was created.
This change was requested in https://github.com/ynput/ayon-core/pull/1242 but misunderstood.
1. The log "Thumbnail has not been created." is not logged if at least one thumbnail was created.
=> Extract Thumbnail: Fix original intnetion of thumbnail created logging

client/ayon_core/tools/utils/projects_widget.py
Don't skip other validations when string regex is filled.
When string match is filled the other filters were skipped, which could reveal archived projects.
The best testing is using archived projects and using AYON launcher 1.1.1 -> That version of AYON launcher does not filter archived projects.
1. Make sure you have at least one archived project.
2. Open launcher tool.
3. Fill part of project name in text filter.
4. You should not see the archived project.
=> Launcher tool: Check for all project filters

client/ayon_core/plugins/publish/extract_thumbnail.py
This PR is to make sure thumbnail would be exported when there is valid representation with image content files.
Resolve https://github.com/ynput/ayon-fusion/issues/16
Representations with `"review"` tag has privilege to be used before any other representation.
Test along with https://github.com/ynput/ayon-fusion/pull/43
1. Build this addon with the relevant fusion addon
2. Launch Fusion
3. Publish
=> Try extract thumbnail from available representations on instance

.github/workflows/update_bug_report.yml
Trigger `Update Bug Report` CI action on `🚀 Release Trigger` action instead of on release.
The action does change `develop` branch which also happens during Relase trigger action which makes new release in the middle. That cause cross push to `develop` branch.
Look at the code changes.
=> CI Update Bug Report: Change trigger event

client/ayon_core/pipeline/create/product_name.py
Reverse keys conversion in product name template to use AYON keys first instead of OP.
We did replace AYON keys to OpenPype keys (probably since OpenPype > AYON conversion) which should have been replaced the other way around for a long time.
Product names should be filled correctly when `{task[name]}`, `{task[type]}`, `{task[short]}` or `{task}` are used in the templates.
1. Choose a host of your choice (I would recommend traypublisher).
2. Fill a product name template in `ayon+settings://core/tools/creator/product_name_profiles` to use one of the keys.
3. Try to create instance in the host.
4. Change to use different key, or combination of keys.
5. Again try to create instance in the host.
Resolves https://github.com/ynput/ayon-core/issues/1264
=> Chore: Reverse product name key replacements

client/ayon_core/plugins/publish/extract_thumbnail.py
Corrects the ffmpeg command-line argument for specifying the seek position. It changes from '--ss' to '-ss', which is the correct flag.
continuation of previous pr #1250
1. test it the same way as in #1250
=> Fixes ffmpeg seek argument

client/ayon_core/pipeline/colorspace.py
The code now uses the correct key ("fallback_type") to access the
fallback type from the configuration data, ensuring the correct config
path is retrieved when no product is found.
Practically settings were not having "type" key, because that one was later renamed to `fallback_type`. This was some residual code.
1. only way to test this is with fallback config type
=> Fixes: Uses correct fallback data key

client/ayon_core/plugins/publish/collect_managed_staging_dir.py
Change staging dir persistence state to debug log instead of info to avoid clutter for the artist (artist doesn't care)
Avoid this clutter in the artist report logs:
+ Some code cosmetics/type hints/typos
1. Publish artist report should look nicer
=> Staging Dir persistence log, change to debug level

client/ayon_core/tools/sceneinventory/view.py
When there is an exception in the `_update_containers` function, only AssertionError was caught. This lead to silent error for the other exception type. This pull request aims at providing visual feedback on the error when the other types of exceptions are caught. 
[src](https://community.ynput.io/t/ayon-manager-silent-error/2586/3?u=bigroy)
1. Use a loader to load an asset into the scene
2. Modify the update code of the plugin to raise a test exception
3. Use the manager to update the asset in the scene
=> Scene inventory tool: Update error more visible

client/ayon_core/hooks/pre_global_host_data.py
Ensures the global host data hook gracefully handles cases where 'folder_entity' or 'task_entity' keys are missing from the input data.
- Prevents potential errors when these keys are not present.
- Uses `.get()` to safely access the values, returning `None` if a key is missing.
1. prehook is possible to start even on context without task or folder
=> Handles missing folder/task data safely

server/settings/main.py, server/settings/publish_plugins.py
Refactor `conditionalEnum` -> `conditional_enum`
Avoid logs like:
```
DEBUG settings.settings_field | Deprecated argument: conditionalEnum
```
1. Check whether settings are still ok
=> Settings: Refactor `conditionalEnum` -> `conditional_enum`

client/ayon_core/pipeline/publish/lib.py
Remove the additional registering of plug-in paths.
Saw this in a deadline log provided by @kalisp 
I think it was due to this logic.
1. Deadline publish jobs should still be running correctly with all relevant plug-ins.
=> Farm Publish: Do not register publish plug-in paths twice

client/ayon_core/pipeline/create/context.py
Fix `IPublishHost` import
Fix:
```
Error: Python: Traceback (most recent call last):
File "F:\dev\ayon-core\client\ayon_core\tools\utils\host_tools.py", line 251, in show_publisher_tool
window = self.get_publisher_tool(parent, controller)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\dev\ayon-core\client\ayon_core\tools\utils\host_tools.py", line 241, in get_publisher_tool
publisher_window = PublisherWindow(
^^^^^^^^^^^^^^^^
File "F:\dev\ayon-core\client\ayon_core\tools\publisher\window.py", line 80, in __init__
controller = QtPublisherController()
^^^^^^^^^^^^^^^^^^^^^^^
File "F:\dev\ayon-core\client\ayon_core\tools\publisher\control_qt.py", line 71, in __init__
super().__init__(*args, **kwargs)
File "F:\dev\ayon-core\client\ayon_core\tools\publisher\control.py", line 96, in …
```
=> Fix `IPublishHost` import

client/ayon_core/cli.py
Define default logging config for AYON processes.
CLI initializes logging config.
1. Logs should be visible in terminal.
=> Chore: Define logging config for AYON processes

client/ayon_core/tools/loader/control.py, client/ayon_core/tools/loader/models/actions.py, client/ayon_core/tools/loader/models/products.py, client/ayon_core/tools/loader/models/selection.py, client/ayon_core/tools/loader/models/sitesync.py, client/ayon_core/tools/loader/ui/_multicombobox.py, client/ayon_core/tools/loader/ui/products_delegates.py, client/ayon_core/tools/loader/ui/products_widget.py, client/ayon_core/tools/loader/ui/search_bar.py, client/ayon_core/tools/loader/ui/window.py
Use `from __future__ import annotations` to fix `list[...]`, `dict[...]` etc. type-hints.
I don't have installed DCC with Python 3.7 so all changes are done based on reading code.
1. Launch a DCC that uses Python 3.7
2. Open loader tool.
3. It should be working.
=> Chore: Fix Python 3.7 in loader tool

client/ayon_core/pipeline/publish/lib.py
Fix all characters of report being printed to new lines
[Fix this change](https://github.com/ynput/ayon-core/commit/6dc0a0e698f624232e284ff1a6c7e130bd9ba592).
1. Publish job log on farm should look normal.
=> Fix all characters of report being printed to new lines

client/ayon_core/plugins/publish/integrate_inputlinks.py
Integrate Input Links: Do not use deprecated `Logger.warn`, use `Logger.warning` instead
This may avoid a deprecation warning like:
```
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
1. Check code change.
=> Integrate Input Links: Do not use deprecated `Logger.warn`, use `Logger.warning` instead

client/ayon_core/pipeline/workfile/__init__.py, client/ayon_core/pipeline/workfile/utils.py
Helper function `save_next_version` is re-using comment from current workfile (or last workfile if current is not set).
This behavior should cover most of function use-cases. It is still possible to pass `comment=""` to avoid that behavior. 
Also added helper functions to workfile's `__init__.py` for easier import.
1. Using `save_next_version` re-uses comment from current workfile.
=> Workfiles: Save next version re-use comment

client/ayon_core/pipeline/context_tools.py
Use the new workfiles API for version up in menus, etc.
After https://github.com/ynput/ayon-core/pull/1378 and https://github.com/ynput/ayon-core/pull/1384 now merged this should now be ready for review.
1. Increment workfile from menu (if enabled in settings should work as intended)
2. Save Workfile action for validator if current file is completely unsaved (has no filename) should work as intended and save a first workfile.
=> Use Workfiles API `save_next_version` in `version_up_current_workfile`

client/ayon_core/pipeline/publish/lib.py
Hash dirpath to plugin before storing it to `sys.modules`.
The issue with current approach is that if there are 2 filenames across all addons then only one will have stored module in sys.modules and only one can retrieve it's path. Hashing dirpath we're making sure that on next discovery we replace the module of the file in `sys.modules` and at the same time is unique enough to avoid clashes with other addons.
1. Add 2 plugins `PluginA` and `PluginB` to different addons (or different folders in one addon) but their filename must be same (e.g. `test_plugin.py`).
2. Run `publish_plugins_discover`, find those plugin classes and try to get their paths.
3. The paths should correspond to their real paths.
```python
import inspect
from ayon_core.pipeline.publish import publish_plugins_discover …
```
=> Publish: Hash publish plugin dirpath before storing to sys modules

client/ayon_core/lib/local_settings.py
Quick maintanance PR for local settings.
- Use dedicated exception `RegistryItemNotFound` for missing registry item value instead of `ValueError`.
- `AYONSettingsRegistry` requires `name` argument -> dangerous for possible clashes if used by multiple places.
- Fix possible issue with registry caching if `set_item` is called (cache for `get_item` was not cleared).
- Removed python 2 compatibility of type hints and super calls.
- Use f-string if possible.
1. Validate code changes.
=> Lib: Local settings code refactor

client/ayon_core/lib/local_settings.py
Try to catch `ItemNotFoundException` exception from `secretstorage` if is available.
Backend `secretstorage` backend does raise error if item is not available, breaking the logic we have implemented. It looks like the `secretstorage` is used if 
Not sure how to test this.
=> Local settings: Capture 'ItemNotFoundException' error if possible

client/ayon_core/host/interfaces/workfiles.py
Make sure the workdir exists before workfile is being saved.
The creation of workdir was lost in void.
1. Launch a DCC.
2. Make sure you don't have existing workdir for a task of your choice.
3. Using workfiles tool select the task and try to save workfile.
4. It should not fail.
=> Workfiles: Make sure workdir exists

client/ayon_core/addon/base.py, client/ayon_core/addon/interfaces.py
First step to remove `get_plugin_paths` method from `IPluginPaths`.
The method was over the time expended to separate methods for each plugin type, now the specific methods do expect more arguments (usually host name) and the `get_plugin_paths` did become deprecated at that moment and also is complicating the readability with related `AddonsManager` method `collect_plugin_paths`.
First of all the method is not abstract anymore, so it is not required to be implemented. Added warning everytime the method is called and returns paths.
Added warning if the output of plugin path getters is string instead of list of strings.
First of all keep `get_plugin_paths` to keep support with older core addon but return empty dictionary. Reimplement `get_create_plugin_paths`, `get_load_plugin_paths`, …
=> Addons: Plugin paths interface

client/ayon_core/pipeline/load/plugins.py, client/ayon_core/pipeline/workfile/workfile_template_builder.py
Adding back linked assets/folder feature that was there in template builder back in OpenPype days. This is now working with template type links of AYON.
This should work nicely with https://github.com/ynput/ayon-ftrack/pull/227
1.links folders together using template links - for example link asset `foo` and asset `bar` to shot `sh010`
2. have some versions of model published in `foo` and `bar`
3. in DCC supporting template builder and loading models create template placeholder working on linked folders.
For example in Maya, you can create this placeholder:
and if you run it in context of `sh010`, it will pull in representations of abc models from `foo` and `bar`.
> [!NOTE]
> To create links, use either API calls `ayon_api.create_link(project_name: str, link_type_name: str, input_id: str, …
=> Linked assets/folders in template builder

client/ayon_core/hooks/pre_ocio_hook.py
This PR is to edit "max" instead of "3dsmax" in host group so that the OCIO-related environment variable being colllected.
This fixes the ocio misconfiguring issue in 3dsmax.
n/a
1. Build Core Addon with this PR
2. Launch 3dsMax
3. The error shown in the screenshot should be gone
=> OCIO: Use "max" for host group to get the correct ocio environment variable

client/ayon_core/addon/base.py
Add support of resolution of environment variables in dev bundle addon paths. You can use standard `{FOO_BAR}` format within the path. This can be used to set dev bundle to work on multiple platforms provided the environment variable is set there.
This also needs PR in `ayon-launcher` https://github.com/ynput/ayon-launcher/pull/253
1. In dev bundle, set path to addons like `{DEV_ADDONS}/ayon-core/client`
2. Set this environment variable so the path exist and can be resolved
3. Run AYON
=> Resolve environment variables in dev bundle addon paths

client/ayon_core/tools/common_models/__init__.py, client/ayon_core/tools/common_models/projects.py, client/ayon_core/tools/loader/abstract.py, client/ayon_core/tools/loader/control.py, client/ayon_core/tools/loader/models/products.py, client/ayon_core/tools/loader/ui/products_model.py, client/ayon_core/tools/sceneinventory/control.py, client/ayon_core/tools/sceneinventory/model.py, client/ayon_core/tools/sceneinventory/models/containers.py
Use project config to visually show product types the same way AYON frontend does.
The feature is available with https://github.com/ynput/ayon-backend/pull/622 but it should work as it was before without it.
1. Make sure you have AYON server with https://github.com/ynput/ayon-backend/pull/622 .
2. Setup product types looks in a project's anatomy.
3. Loader should visually show the products the way you define it in anatomy.
=> Loader: Product type icons

client/ayon_core/tools/utils/delegates.py
Elide status name text.
Use-case is that status without an icon and short name is just hidden from the UI if the text does not fit the width of column. 2 things were changed, if short name is not available then use full name. If text does not fit into the text rectangle then elide the text to the width. Elided text must have at least one of the text characters.
1. Set short name of status to empty string `""`.
2. Open loader, make the status column smaller.
3. It should keep the text filled but should be elided (added 3 dots at the end).
=> Loader: Elide status name text

client/ayon_core/hooks/pre_add_last_workfile_arg.py, client/ayon_core/pipeline/actions.py, client/ayon_core/tools/launcher/abstract.py, client/ayon_core/tools/launcher/control.py, client/ayon_core/tools/launcher/models/__init__.py, client/ayon_core/tools/launcher/models/actions.py, client/ayon_core/tools/launcher/models/selection.py, client/ayon_core/tools/launcher/models/workfiles.py, client/ayon_core/tools/launcher/ui/actions_widget.py, client/ayon_core/tools/launcher/ui/hierarchy_page.py, client/ayon_core/tools/launcher/ui/window.py, client/ayon_core/tools/launcher/ui/workfiles_page.py
Show task workfiles in launcher UI.
The request is to show which hosts were used on a task. By showing workfiles user gets 2 information at a time. The workfiles must be saved using workfiles tool, and for icon it has to be saved using new workfiles api.
To see applications actions you must have https://github.com/ynput/ayon-applications/pull/98 and the workfile entities must have stored host name (using new workfiles api).
It might make sense to hide it and keep window size as was and expand it only if user "enables" that.
1. You can see workfiles when task is selected in launcher.
Resolves https://github.com/ynput/ayon-core/issues/1229
=> Launcher: Show task workfiles

client/ayon_core/tools/launcher/ui/actions_widget.py
Fix used key to get action label.
Key `"action_label"` was changed to `"full_label"` but the changes was not propagated in .
1. Actions that do show forms can be triggered.
=> Launcher: Fix form handling

client/ayon_core/scripts/otio_burnin.py
Use new import of otio adapters in the code.
Change of the import is/was required since https://github.com/ynput/ayon-core/pull/1424 .
1. Create new dependency package using ayon-core 1.6.0 or newer.
2. Burnins should be created ok.
=> Burnins: Fix import of adapters
