client/ayon_core/addon/base.py

Addon can be registered under 2 names in `AddonsManager`.
This is needed for `sitesync` addon which was named `sync_server` in OpenPype. With this change it is possible to do both:
```python
from ayon_core.addon import AddonsManager
manager = AddonsManager()
sync_server = manager["sync_server"]
sitesync = manager["sitesync"]
print(sync_server is sitesync)
>>> True
```

Chore: Addons can define their openpype alias name

---

client/ayon_core/settings/__init__.py
client/ayon_core/settings/ayon_settings.py

Removed unnecessary code from ayon settings conversion helpers.
All removed conversion helpers are happening automatically right now and are not needed.
1. Project settings load correct values from AYON server

Cleanup AYON settings

---

client/ayon_core/hosts/maya/api/plugin.py

Fix check of type in maya load colors.
1. Colors in maya loaders are loaded correctly

Maya: Fix type check

---

client/ayon_core/tools/publisher/control.py

Port of https://github.com/ynput/OpenPype/pull/6236

Publisher: "Action Failed" is working

---

client/ayon_core/hosts/fusion/plugins/load/load_sequence.py
client/ayon_core/lib/applications.py

Fix typo in applications `"project_doct"` > `"project_doc"` and typo in fusion load plugin `"onilne"` > `"online"`.
1. Applications can be launched.
2. Fusion load plugin can be discovered on online product type.

Chore: Minor fixes

---

client/ayon_core/lib/execute.py
client/ayon_core/plugins/publish/collect_comment.py

Fix `CollectInstanceCommentDef` plugin and fix docstring of `run_detached_process`.
1. `CollectInstanceCommentDef` plugin is loaded in publisher.
2. Function `run_detached_process` shows correct typehints in IDE.

Chore: Minor fixes 2

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/enhancement_request.yml

Improve clarity and consistency in issue reporting templates.

Update issue template titles to remove prefixes.

---

client/ayon_core/hooks/pre_new_console_apps.py
client/ayon_core/hosts/zbrush/addon.py
client/ayon_core/hosts/zbrush/api/communication_server.py
client/ayon_core/hosts/zbrush/api/lib.py
client/ayon_core/hosts/zbrush/api/plugin.py
client/ayon_core/hosts/zbrush/hooks/zbrush_startup_script.py
client/ayon_core/hosts/zbrush/plugins/publish/collect_current_file.py
client/ayon_core/hosts/zbrush/plugins/publish/extract_model.py
client/ayon_core/hosts/zbrush/plugins/publish/extract_polymesh.py
client/ayon_core/hosts/zbrush/plugins/publish/validate_edit_mode.py

THanks for @BigRoy 
Paragraphs of text giving context of additional technical information or code examples.
1. start with this step
2. follow this step

Roy's adjustment to zbrush integration

---

server_addon/maya/server/settings/render_settings.py

Spotted by community; https://discord.com/channels/517362899170230292/563751989075378201/1218067303527219260
Nothing to test as its just a label change.

Update Maya Redshift render settings label.

---

client/ayon_core/hosts/maya/api/plugin.py

Fix maya initialization issue caused by https://github.com/ynput/ayon-core/pull/165.
Missing comma in arguments.
1. Maya is integrated correctly (AYON menu is available)

Maya: Fix initialization

---

client/ayon_core/hosts/harmony/plugins/load/load_template_workfile.py
client/ayon_core/hosts/houdini/api/plugin.py
client/ayon_core/hosts/houdini/plugins/create/create_hda.py
client/ayon_core/hosts/maya/plugins/publish/collect_multiverse_look.py
client/ayon_core/hosts/photoshop/plugins/publish/collect_auto_image.py
client/ayon_core/hosts/photoshop/plugins/publish/collect_auto_image_refresh.py
client/ayon_core/modules/deadline/deadline_module.py
client/ayon_core/modules/deadline/plugins/publish/collect_default_deadline_server.py
client/ayon_core/modules/deadline/plugins/publish/validate_expected_and_rendered_files.py
client/ayon_core/modules/deadline/repository/custom/plugins/OpenPypeTileAssembler/OpenPypeTileAssembler.py

Cleanup some cosmetic / redundant / dead code
See commit messages for details.
1. Shouldn't do much
2. Maybe double check load workfile template for harmony?

Chore: Cleanup redundant code

---

client/ayon_core/hosts/fusion/plugins/create/create_image_saver.py

Remove unused import
Variable/import was unused.
1. Image Creator should work fine in publisher

Chore: Code cleanup - remove unused import

---

client/ayon_core/hosts/maya/plugins/load/load_vdb_to_arnold.py

Fix refactored argument name
1. Maya Load VDB to Arnold should work for loading and updating

Bugfix: Maya Load VDB to Arnold refactored argument name

---

client/ayon_core/hosts/maya/plugins/publish/validate_step_size.py

Fix select invalid action for when instance node name changed from creation.
Also improve messaging in the validation reports.
1. Validate step size should work for renamed instance nodes.
2. Validation message should be clear.

Maya: Validate step size - correct instance node

---

client/ayon_core/hosts/maya/plugins/publish/validate_no_namespace.py

Improve readability of the artist facing report for the Validate No Namespace validator in Maya.
n/a
1. Publish a model with a namespace on geometry
2. Validator should detect it and report a meaningful message.

Maya: Improve validate no namespace report for artists

---

client/ayon_core/hosts/houdini/plugins/load/actions.py
client/ayon_core/hosts/nuke/api/lib.py

Fix used variables. Issues were discovered during ruff linter validations.
NOTE: Based on PR https://github.com/ynput/ayon-core/pull/196 .

Chore: Quick fixes

---

client/ayon_core/hosts/maya/plugins/publish/validate_no_null_transforms.py

Tiny optimization to validate no null transforms for models with many transforms
n/a
1. Empty transforms should still be detected by the validator

Maya: optimize validate no null transform

---

client/ayon_core/hosts/maya/plugins/publish/collect_render.py
client/ayon_core/hosts/maya/plugins/publish/validate_render_single_camera.py

Provide a validation report when no renderable cameras are set instead of erroring during collectors.
Resolves the issues mentioned [here](https://github.com/ynput/ayon-core/pull/299#issuecomment-2026900524).
Note that you may still get an error from another validator which would be fixed by https://github.com/ynput/ayon-core/pull/299
As such, it actually makes easier testing if you merge both - and validate both together.
1. Create a renderlayer
2. In the renderlayer create an override that disables all renderable cameras.
3. Remain in the default layer with a renderable camera - otherwise you might hit another error that gets fixed by another PR https://github.com/ynput/ayon-core/pull/299
4. Publish/Submit the renderlayer
It should now show you a validation that the renderlayer has no …

Maya: Render Improve Validation Report if no cameras are set

---

client/ayon_core/settings/lib.py

Fix typo and remove empty lines in settings lib file.

Chore: Settings core cleanup

---

client/ayon_core/hosts/hiero/plugins/create/create_shot_clip.py

Fix some typos on Hiero plugin

Fix typos on Hiero plugin

---

client/ayon_core/plugins/publish/extract_review.py

This exposes the `frame_start_handle` (frame start including handles) converted to timecode like `HH:MM:SS:FF` to be used for FFMPEG args formatting.
This allows to specify e.g. `--timecode {timecode}` in the formatting arguments in settings to write the timecode metadata into the output file so that other applications can pick this up.
We use this for loading review files into Resolve - by having this timecode metadata included then Resolve 'understands' what the start frame / timecode is of the loaded media.
1. Add `--timecode` and `{timecode}` args to ffmpeg formatting arguments in settings
2. Publish a review.
3. The timecode metadata should be written with the output file.

Extract Review: Expose `timecode` for formatting ffmpeg args

---

client/ayon_core/pipeline/anatomy/anatomy.py

Use correct variable name where site sync addon is stored.

Anatomy: Fix variable used to work with site sync

---

client/ayon_core/tools/loader/ui/products_model.py

Get version related information once for all products instead of per item.
This is a draft that was not tested, but should enhance speed of the UI.
1. Compare speed of Loader before and after this PR.
2. Validate that it actually shows correct information, especially when sitesync is enabled.

Loader: Products model fetches versions information once

---

client/ayon_core/hosts/blender/plugins/load/load_layout_json.py

Fixed used variable in layout loader plugin.
1. Load layout plugin works.

Blender: Fix used load layout plugin

---

pyproject.toml

Added list of files that should be ignored for ruff when.
PR related to https://github.com/ynput/ayon-core/pull/196 .
- Validate if excluded paths make sense to be ignored.
- Validate that ruff is actually ignoring them.

Ruff: Add list of files to exclude from linting

---

client/ayon_core/hosts/max/plugins/publish/extract_alembic.py

Fix https://github.com/ynput/ayon-core/issues/161
n/a
1. Launch Max
2. Create Model Instance
3. There should be optional toggle for Extract Geometry(Alembic) in the Publish tab in Publisher UI

Max: Extract Geometry (Alembic) toggles in the Publisher UI

---

client/ayon_core/hosts/max/api/lib.py
client/ayon_core/hosts/max/api/pipeline.py

Fixed https://github.com/ynput/ayon-core/issues/399
n/a
1. Launch Max
2. Create Instance with some assets in scene
3. Rename your assets
4. Go to the container which stores the ayon-related modifiers
5. The filtering of the asset for `Add to Container` and `Delete from Container` should be shown correctly
6. Publish your instance
7. Should be published successfully without errors

Max: Make sure the AYON data in the instance node stores correct asset data after the rename of the asset

---

client/ayon_core/hosts/max/plugins/load/load_model_fbx.py
client/ayon_core/hosts/max/plugins/load/load_model_obj.py
client/ayon_core/hosts/max/plugins/load/load_model_usd.py
client/ayon_core/hosts/max/plugins/load/load_pointcache_ornatrix.py

Fix the error encountered when updating the loaded assets.
n/a
1. Launch Max
2. Load any assets with fbx & usd & obj & poincache ornatrix loaders
3. Setting version with these assets
4. Should be updated successfully

Max: Fix the error encountered when updating the loaded assets

---

server_addon/maya/server/settings/publishers.py

Adding missing default value for settings in #474

Add default value for #474

---

client/ayon_core/hosts/max/api/lib.py
client/ayon_core/hosts/maya/plugins/create/create_animation_pointcache.py
client/ayon_core/hosts/traypublisher/csv_publish.py
client/ayon_core/modules/deadline/plugins/publish/submit_publish_job.py
client/ayon_core/modules/deadline/plugins/publish/validate_deadline_pools.py

Remove unused imports and cleaned up some formatting.
These were reported by automated linter.

Chore: Ruff cleanup

---

package.py

Updated versions in package.py .
Added AYON launcher version dependency to package.py and use ayon attribute to descrive requested server version.
1. Create package of ayon core
2. Upload the package to server
3. Create new bundle and select uploaded core version
4. If AYON launcher is not selected or is selected older version, it should complain that bundle contains incompatible versions

Chore: Add version dependency

---

client/ayon_core/hosts/traypublisher/plugins/create/create_editorial_package.py
client/ayon_core/hosts/traypublisher/plugins/publish/extract_editorial_pckg.py
client/ayon_core/hosts/traypublisher/plugins/publish/validate_editorial_package.py
server_addon/traypublisher/server/settings/publish_plugins.py

Cleanup code for ruff after https://github.com/ynput/ayon-core/pull/484.

Chore: Fix ruff comments

---

server_addon/tvpaint/client/ayon_tvpaint/__init__.py
server_addon/tvpaint/client/ayon_tvpaint/addon.py
server_addon/tvpaint/client/ayon_tvpaint/plugins/load/load_image.py
server_addon/tvpaint/client/ayon_tvpaint/plugins/load/load_reference_image.py
server_addon/tvpaint/client/ayon_tvpaint/version.py
server_addon/tvpaint/package.py
server_addon/tvpaint/pyproject.toml

Added settings category to load plugins, added pyproject.toml and added version to client addon.

TVPpaint: Fixes after movement

---

server/settings/publish_plugins.py

Tweak settings title for `Validate Outdated Containers`
See https://github.com/ynput/ayon-core/pull/530#discussion_r1606810330
Note I didn't bump any addon versions since it's cosmetic only. (Plus it's core which I believe we shouldn't bump in PRs anymore?)
1. Create server package
2. Watch it in all it's glory

Tweak settings title for `Validate Outdated Containers`

---

server_addon/aftereffects/client/ayon_aftereffects/version.py
server_addon/applications/client/ayon_applications/version.py
server_addon/maya/client/ayon_maya/version.py

Chore: Fix client versions

---

server_addon/maya/client/ayon_maya/plugins/create/create_animation_pointcache.py
server_addon/maya/client/ayon_maya/plugins/create/create_look.py
server_addon/maya/client/ayon_maya/version.py
server_addon/maya/package.py

Pointcache does not append attr definitions to base list but to new list.
1. Create pointcache in maya.
2. Workfile instance should not suddenly have attributes.

Maya: Pointcache create plugins fix

---

server_addon/maya/client/ayon_maya/api/lib.py
server_addon/maya/client/ayon_maya/version.py
server_addon/maya/package.py

Fix version comparison in Maya lib.
The version comparison breks assign look UI.
1. Assign look UI should not crash

Maya: Convert version string to integer

---

server/settings/publish_plugins.py

Fix wrong kwarg used in settings model.

Settings: Use 'title' instead of 'topic'

---

client/ayon_core/plugins/load/delivery.py

Deliver versions: Remove legacy code
Legacy data should not exist in AYON. **However,** I'm not sure if there's any way to still generate representations without 'files'.
1. Deliver versions should still work

Deliver versions: Remove legacy code

---

client/ayon_core/hooks/pre_add_last_workfile_arg.py

Open last workfile on launch for Cinema4D
n/a
1. Last workfile opens on C4D launch

Cinema4D: Open last workfile on launch

---

client/ayon_core/lib/log.py
client/ayon_core/lib/path_tools.py

Remove Python 2 compatibility code
Cleanup.
1. Logger should still work
2. Hardlinking should still work on Windows.
Or just validate the code changes?

Remove Python 2 compatibility code

---

client/ayon_core/lib/transcoding.py

Add entry for SXR image extension.
resolve: https://github.com/ynput/ayon-nuke/issues/69
Needs to be tested alongside:

Chore: Add SXR to image extension

---

client/ayon_core/plugins/publish/extract_thumbnail.py

resolve #1168
1. Everything should work as usual

remove usage of a deprecated tag: `thumb-nuke`

---

client/ayon_core/pipeline/create/context.py

Collect publish attributes when all add bulk context managers end.
Each add bulk context manager triggers publish attribute collection for all added instances in that single context, but that should happen at the bulk fully ends.
Positive side effect is that is makes the collection a lot faster.
This might be tricky to test as it might reveal possible issues during collection phase. In ideal case scenario we should test all possible instances in all hosts, especially those that have additional logic in collect instances. But I don't think this change does affect them in any way. Creators should not be dependent on publish attributes, so technically nothing should break.
- Collection of instances should not break anything.
Resolves https://github.com/ynput/ayon-core/issues/1186

Create context: Do not trigger publish attributes collection after each add bulk

---

client/ayon_core/plugins/publish/extract_thumbnail.py
client/ayon_core/plugins/publish/extract_thumbnail_from_source.py

Update ffmpeg commands to work with newer ffmpeg releases.
Stop using deprecated commands (that were deprecated many years ago).
1. It should be possible to create thumbnails from video files.

Chore: Update ffmpeg commands

---

client/ayon_core/plugins/publish/integrate_thumbnail.py

Thumbnail integration works for more jpeg types.
Validation of jpeg is too strict in ayon api and does not allow all possible jpeg format which are created by default by new ffmpeg.
1. All sorts of jpeg files can be integrated as a thumbnail.

Chore: Fix thumbnail upload

---

client/ayon_core/pipeline/farm/pyblish_functions.py

Remove redundant duplicate lines of code in `_get_legacy_product_name_and_group`
...
1. Check code

Remove redundant duplicate lines of code

---

client/ayon_core/plugins/publish/extract_review.py

Extract Review: Use data class for temp data to get some type hints
Review changes and please test.
Also, this code really is a labyrinth admittedly... 🍝 
1. Test a variety of review publishes, single files, sequences, from tray publisher to maya renders, etc.

Extract Review: Use data class for temp data to get some type hints

---

client/ayon_core/pipeline/create/context.py

Updated type hints in CreateContext.
Added more type hints to CreateContext and use annotations import to use built-in type hints.
1. Check the changes in code.

Create context: Updated type hints

---

client/ayon_core/pipeline/workfile/utils.py

Fill `"ext"` key in template data in helper functions.
1. Functions `save_next_version` and `copy_workfile_to_context` do work.

Workfile: Fill extension in helper functions

---

client/ayon_core/tools/launcher/models/actions.py

Allow to show webactions based on current settings variant.
This will start to work with next release of AYON server.
1. Make sure you have current develop of ayon-backend.
2. Launcher shows actions based on your production, staging or dev bundle.
Part of fix related to https://github.com/ynput/ayon-backend/issues/651 .

Launcher tool: Pass variant to actions list

---

client/ayon_core/tools/utils/nice_checkbox.py

Enhancement of size and position calculation, colors loading/caching and code formatting.
Noticable chang might be that the checkbox should not look like it is cut off by one pixel.
1. It looks nice  as before (or nicer).

Nice Checkbox: Small enhancements of Nice Checkbox
